### ISSUE TITLE
Expiring domain, seeking transfer

### ISSUE THREAD

**Issue by rossabaker** [scalatra/scalatra#1015]
Hi,

scalatra.org is set to expire on June 30, and I'd like to transfer it to somebody more involved in the maintenance of the project than I've been in the last several years.  I can be reached on Gitter or via Twitter DM at `@rossabaker`.

Thanks!

**Comment by takezoe** [comment]
@rossabaker I sent a DM to you on Gitter.

**Comment by rossabaker** [comment]
We were able to hand it over. Thanks, @takezoe!
