### ISSUE TITLE
fileParams doesn't provide function to get the list of values

### ISSUE THREAD

**Issue by acote-coveo** [scalatra/scalatra#1022]
Previously, the `fileParams` was inheriting from the *Map* trait. 

Therefore, a commit removed this inheritance and removed the possiblity to list the values.

For instance, we can receive different file params with different names. Thus, we can't get the value by it's key.

It would be nice to provide the wrapped iterator.

**Note**: I can provide a PR during the weekend for that.

**Comment by takezoe** [comment]
@acote-coveo Great! We are looking forward to see your pull request.

**Comment by takezoe** [comment]
Oh, https://github.com/scalatra/scalatra/pull/1023 is it. Thanks!

**Comment by takezoe** [comment]
By the way, why simply using `fileMultiParams` instead of `gilrParams` doesn't work?

**Comment by acote-coveo** [comment]
@takezoe  I don't know how it's map at the Swagger level but we support only one file param, not multiple values. We simply don't know what could be the filename passed and this is why we need to be able to get the first values without know the key(filename).

**Comment by takezoe** [comment]
@acote-coveo Sorry for my late comment. I just thought you can like below regardless it's a single value param or multiple values param:
```scala
fileMultiParams.iterator.foreach { case (fileName, params) =>
  println(s"${fileName}: ${params.headOption}")
}
```
Anyway, having `.iterator` on `FileSingleParams` makes sense. Thanks for your contribution!
