### ISSUE TITLE
Deprecate Scalate

### ISSUE THREAD

**Issue by takezoe** [scalatra/scalatra#1066]
Scalate has a strong dependency to Scala compiler so it usually requires a specific minor version of Scala and Scalate team is actually struggling to support newer versions of Scala. This also means it will be challenging to support Scala 3 in Scalate.

Due to these reasons, it would be better to prepare to be away from Scalate. I think we should make Twirl as a default template engine in Scalatra. What we need to do for that is:

- Update documentation and examples to use Twirl
- Deprecate Scalate related classes in Scalatra codebase

Scalatra 2.7.x would be a good target to deprecate Scalate and maybe we can fully drop Scalate support in Scalatra 2.9.

Deprecating Scalate will also reduce our future maintenance cost because we only need to support Twirl in codebase, documents and even examples.

**Comment by magnolia-k** [comment]
In Scalatra 2.8 branch, Scalate is now deprecated.

Also, I added a note on the Scalatra-Website that it will no longer be supported in future versions.

**Comment by dlnorgaard** [comment]
Is there documentation somewhere on how to replace ScalateSupport?

**Comment by takezoe** [comment]
@dlnorgaard There is no documentation because Twirl which is our recommended template engine after Scalate deprecation doesn't require special integration with Scalatra. If your Scalate templates strongly depend on Scalatra's Scalate integration, it may be a bit hard to migrate those templates to Twirl, though.

By the way, Scalate will be actually dropped in Scalatra 3.0. So you can continue to use Scalate as long as you stay at Scalatra 2.8.x. What is your plan?

**Comment by dlnorgaard** [comment]
I'm working on a legacy app and am not very familiar with how the Scalatra part of the codebase works. I guess I'll have to learn at some point. We just migrated to 2.8.x and may migrate to 2.9.x when it comes out if Scalate isn't dropped there (tho I've read in places that it will be).  We haven't discussed migrating to Scala 3.0 so I imagine that is in distant future.

**Comment by takezoe** [comment]
We will maintain Scalatra 2.8.x for Scala 2.12/2.13 and will release Scalatra 3.0.x for Scala 3, and Scalate support will be maintained in Scalatra 2.8.x. 

Therefore, if you have no immediate plan to move to Scala 3 (= Scalatra 3.0), you can continue to use Scalate with Scalatra 2.8.x. We have no plan to stop Scalatra 2.8.x maintenance at this point.
