### ISSUE TITLE
Issue with mongoDB example on website

### ISSUE THREAD

**Issue by Xenate** [scalatra/scalatra#1068]
I followed to instructions for incorporating mongodb into my scalatra project but I got the following error:
not found: type MongoController
[error]     context.mount(new MongoController(mongoColl), "/*")

I used the import:
import org.scalatra.example.MongoController

Can somebody help me?

**Comment by takezoe** [comment]
Maybe I answered your question on StackOverflow.
https://stackoverflow.com/questions/65243196/scalatra-mongodb-not-working-mongocontroller-not-in-package-example
