### ISSUE TITLE
Deprecate Atmosphere

### ISSUE THREAD

**Issue by magnolia-k** [scalatra/scalatra#1083]
The Atmosphere is currently not very actively maintained.

And Atmosphere is the most significant obstacle to making Scalatra compatible with the latest Servlet APIs.

Also, Atmosphere supports a variety of middleware and protocols, which makes it too complex to simply use WebSockets.

We could introduce a simpler WebSocket mechanism (e.g. a simple wrapper for the functionality provided by Jetty) and stop supporting Atmosphere.

**Comment by dlnorgaard** [comment]
Hi.  Just wanted to confirm the plans for this.  I am not seeing org.scalatra.atmosphere.AtmosphereClient being marked deprecated in 2.8.4.

**Comment by takezoe** [comment]
@dlnorgaard `AtmosphereSupport` which is required to use Atomosphere integration in Scalatra has been marked as deprecated: https://github.com/scalatra/scalatra/commit/0f7d7883fd85ae8511b3ddb75119751f080d786c

The status is the same as Scalate integration. It will be maintained in Scalatra 2.8.x and dropped in Scalatra 3.0.
