### ISSUE TITLE
Scala 3

### ISSUE THREAD

**Issue by xuwei-k** [scalatra/scalatra#1211]

**Comment by takezoe** [comment]
I'm considering releasing a milestone (or early access) version of Scala 3 version of Scalatra.

One concern is the version number. Which version is more suitable for the next major release that is expected to support Scala 3, 2.8.0 or 3.0.0?

**Comment by magnolia-k** [comment]
Release 2.8.0 at this stage, deprecate modules in 2.9.0 that may be difficult to update in the future (e.g. atmosphere), and release 3.0.0 to support Scala3.

**Comment by takezoe** [comment]
That sounds a long way but makes sense.

I was looking for a strategy to provide Scalatra for Scala 3 experimentally but looks like there are things we have to do before it. I will hold off releasing Scala 3 version of Scalatra until 3.0.0.

By the way, what were the major changes in Scalatra 2.8.0? To be honest, I was not following recent updates closely...

**Comment by magnolia-k** [comment]
The main change since Scalatra 2.7 is to improve incompatible notation for Scala3
In addition, Scalate and others have been deprecated for future upgrades.

**Comment by takezoe** [comment]
Okay. Let's begin preparation for Scalatra 2.7.0, then.

**Comment by xuwei-k** [comment]
👀 🤔 

https://repo1.maven.org/maven2/org/scalatra/scalatra_3/

**Comment by xuwei-k** [comment]
- https://github.com/erikvanoosten/metrics-scala/pull/365
- https://github.com/akka/akka/pull/30817

**Comment by xuwei-k** [comment]
- https://github.com/scalatra/scalatra/pull/1372

**Comment by xuwei-k** [comment]
removed all `CrossVersion.for3Use2_13`. release next milestone version with Scala 3? 🤔

**Comment by xuwei-k** [comment]
https://github.com/scalatra/scalatra/releases/tag/v3.0.0-M1
