### ISSUE TITLE
Named capturing groups

### ISSUE THREAD

**Issue by rossabaker** [scalatra/scalatra#147]
Ruby 1.9 supports named capturing groups, which [Sinatra handles](http://www.sinatrarb.com/blog#named_captures_on_19)

This feature is introduced in [Java 7](http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#groupname).  We could sniff for Java7, or consider [JRegex](http://jregex.sourceforge.net/).  Not sure how compatible JRegex is with java.util.Regex.

Low priority.

**Comment by magnolia-k** [comment]
At this point, the issue is closed because the discussion has not progressed for a long time.
Please raise another issue if further discussion is needed.
