### ISSUE TITLE
After filters run synchronously on asynchronous requests

### ISSUE THREAD

**Issue by rossabaker** [scalatra/scalatra#148]
- Is this really a bug, or do users just need to understand that's how after filters work?
- How do we reliably detect that an action ran asynchronously?  Currently, async behavior is triggered by returning an Akka Future.  What about scala.actor.Futures and java.util.concurrent.Futures and ad hoc asynchronous Servlet API invocations?

**Comment by DWvanGeest** [comment]
It seems to me like this could still be an issue. I'm using `FutureSupport` and seeing that the `after` callback runs synchronously, before the async action has completed. 

I'm wondering if this fix is specific to Akka, or if it fixes the general case when just using Scala futures.
