### ISSUE TITLE
Consider releasing a Jakarta-based flavour of Scalatra 3.x

### ISSUE THREAD

**Issue by dalbani** [scalatra/scalatra#1484]
For various (historical) reasons, I have a Scalatra-based codebase that is integrated in a Spring Boot 2.7 application.
With the recent release of Spring Boot 3, which is built on top on Jakarta EE APIs, this integration is not possible anymore, as Scalatra relies on `javax.servlet` in particular.
I saw in https://github.com/scalatra/scalatra/pull/1425 that the upgrade to Servlet 5.0 / Jetty 11 has been reverted, to rather focus the effort on supporting Scala 3.
I'm personally not really interested in the latter, but being able to run in Jakarta environment *is* something I'd very much like.

"For the fun", I've tried to apply the changes contained in the pull request mentioned above, but on top on the v2.8.x branch.
See https://github.com/dalbani/scalatra/pull/2 for the code if you're interested.
And it seems to work – at least all the test pass 😅

It's obviously not as simple as, in particular than Java 11+ becomes a requirement, and Scalate and Atmosphere had to be dropped.
But still, what do you think of this idea?

Thanks!

**Comment by takezoe** [comment]
Maintaining many variations of codebase is hard with the current our engineering resource, but we know there are needs both Servlet 4.0 and Jakarta because many existing Java softwares haven't been migrated to Jakarta.

My current plan is shifting Scalatra 2 to the maintenance mode and providing both Servlet 4.0 and Jakarta versions of Scalatra 3 in the future.

As you know, Scalatra 3 is mostly compatible with Scalatra 2 though some features which are not easy to keep maintained are dropped. So I think you can migrate your application to Scalatra 3 easily if you don't need Scalate/Atmosphere support.

Does providing Jakarta version of Scalatra 3 work for you?

**Comment by takezoe** [comment]
Created a branch. I'm considering to release this branch as `3.0.0-M4-jakarta`.

**Comment by dalbani** [comment]
Sounds great!

**Comment by takezoe** [comment]
`3.0.0-M4-jakarta` has been published to Maven central.

**Comment by dalbani** [comment]
Excellent, thanks a lot 👍--
Damiano Albani

**Comment by xuwei-k** [comment]
- https://github.com/scalatra/scalatra/pull/1536

**Comment by dalbani** [comment]
Scalatra 3 is going to be released with both support for `javax` and `jakarta` packages, so I can close this issue.

**Comment by dalbani** [comment]
I had just closed the issue yesterday, that something came to my mind.
Is the choice of putting either `javax` or `jakarta` in the artifact's *version* a good idea?
Which well eventually become `3.0.0-javax` and `3.0.0-jakarta`.

I'm afraid that this is not in line with SemVer: see https://semver.org/#spec-item-9 in particular for the paragraph regarding what would be considered a "pre-release" version with this naming scheme.

One of the issues with not conforming to SemVer, is that it will break tools like Dependabot or Renovate Bot, which — should they support pre-releases — will probably consider `3.0.0-javax` as having a higher version that `3.0.0-jakarta`.

To put things in perspective, other libraries chose for putting the `jakarta` qualifier in the artifact's ID.
As in:
- `io.prometheus:simpleclient_servlet_jakarta`
- `io.swagger.core.v3:swagger-core-jakarta`
- `io.sentry:sentry-spring-boot-starter-jakarta`

A new release of Twirl is imminent, so things will be soon ready for a Scalatra 3 release.
Let's make a future proof choice for this `javax` / `jakarta` naming scheme.

@xuwei-k: do you think it would possible to do like you did in https://github.com/scalatra/scalatra/pull/1536, but using the artifact ID?

**Comment by mkurz** [comment]
Twirl 1.6.0 released: https://github.com/playframework/twirl/releases/tag/1.6.0

**Comment by takezoe** [comment]
Does #1573 make sense?
