### ISSUE TITLE
Scalatra 3.0.0-Mx artifacts contain Java 17 bytecode

### ISSUE THREAD

**Issue by dalbani** [scalatra/scalatra#1528]
I was recently trying out 3.0.0-M3 in a Scala 2.12 / Java 11 environment and I got the following error:
```
java.lang.UnsupportedClassVersionError: org/scalatra/swagger/runtime/annotations/ApiModel has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
My understanding is that https://github.com/scalatra/scalatra/commit/de00106c13242ab608c24daa51b79fdd716fc8aa#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91 from @xuwei-k changed how `-target:jvm-1.8` (now `-target:8` in *master*) is configured, as it went from `scalacOptions` to `unusedOptions`.

Could you fix that? Thanks!

**Comment by xuwei-k** [comment]
@takezoe please merge https://github.com/scalatra/scalatra/pull/1529 and release new version 🙏

**Comment by takezoe** [comment]
Released 3.0.0-M4. Artifacts will be available on Maven central shortly.

**Comment by dalbani** [comment]
Thanks a lot for this very quick action!
When do you think the official release of Scalatra 3 will take place?

**Comment by takezoe** [comment]
The only reason why we cannot release GA is Scala3 compatible version of [Twirl](https://github.com/playframework/twirl) is still RC. We can release Scalatra 3.0.0 immediately once Twirl 1.6.0 is released.

**Comment by dalbani** [comment]
OK, thanks for the answer. I can close this issue now.

Speaking of versions and releases, I'm curious what you think of I wrote in https://github.com/scalatra/scalatra/issues/1484.

**Comment by mkurz** [comment]
Twirl 1.6.0 released: https://github.com/playframework/twirl/releases/tag/1.6.0
