### ISSUE TITLE
Release Scalatra 3.1.0

### ISSUE THREAD

**Issue by dalbani** [scalatra/scalatra#1675]
Hello,

My message back in https://github.com/scalatra/scalatra/pull/1632#issuecomment-1979002721 may have been overlooked, so I thought I would open a dedicated issue for better visibility.
In short: could you release Scalatra 3.1.0? 😄

Thanks a lot!

**Comment by dalbani** [comment]
I've just discovered an issue with Scalatra when running tests in any environment with Jetty 12.0.8: https://github.com/scalatra/scalatra/pull/1678.
Before releasing Scalatra 3.1.0, it would probably be a good idea to have an intermediary `3.1.0-M2` with this fix.
What do you think @takezoe or @xuwei-k?

**Comment by dalbani** [comment]
Hey, friendly ping here 👋
Tell me if I can help with the release.

**Comment by dalbani** [comment]
Hey @takezoe, I'm glad to see that you assigned this issue to you.
I hope you can find some time to get it through the door. Thanks!

**Comment by takezoe** [comment]
Published: https://github.com/scalatra/scalatra/releases/tag/v3.1.0

**Comment by dalbani** [comment]
Excellent, thanks a lot for the release! 🙇
