### ISSUE TITLE
Release Scalatra 3.1.1(?)

### ISSUE THREAD

**Issue by dalbani** [scalatra/scalatra#1750]
As I alluded to in https://github.com/scalatra/scalatra/pull/1746, Jetty 12.0.15 includes a breaking changes which required a fix in Scalatra.
The recently released Spring Boot 3.4 also includes Jetty 12.0.15, so that would be great if you could make a release of Scalatra so I can upgrade my Spring Boot app which uses Scalatra.
Thanks a lot!

**Comment by dalbani** [comment]
Hi, friendly reminder here 👋

**Comment by magnolia-k** [comment]
@takezoe

**Comment by takezoe** [comment]
I'll release Scalatra 3.1.1 tomorrow or this weekend.

**Comment by takezoe** [comment]
Tagged: https://github.com/scalatra/scalatra/releases/tag/v3.1.1

**Comment by takezoe** [comment]
I'm struggling to publish artifacts to sonatype. Will try it again tomorrow or next week.

**Comment by takezoe** [comment]
Published and released. It will be available in Maven Central within a few hours.

**Comment by dalbani** [comment]
Great, thanks a lot for your effort!
