### ISSUE TITLE
Add metrics (codahale)

### ISSUE THREAD

**Issue by casualjim** [scalatra/scalatra#204]
Expose a bunch of metrics through the codahale metrics library.

requested by @waywardmonkeys

Which metrics to track?
- time taken for a request
- number of concurrent requests
- number of requests processed

**Comment by Evildethow** [comment]
Any updates?

**Comment by rossabaker** [comment]
@japhar81 added this support, which will be included in Scalatra 2.4. It's available in the snapshots now.

**Comment by bfritz** [comment]
To close the loop, looks like #441 and #442 are the relevant PRs.
