### ISSUE TITLE
Make all error messages configurable through i18n

### ISSUE THREAD

**Issue by casualjim** [scalatra/scalatra#209]
Collect all the messages we return and put them in a resource bundle.
This is related to #144

**Comment by zaggy** [comment]
Hi, I wanted to start contributing to this project and feel like I can get this one done. You may assign myself on this issue.

**Comment by seratch** [comment]
@zaggy This issue was opened over 3 years ago. I18nSupport already exists in scalatra-core now. If you have any ideas or suggestions to current implementation, please open another issue.
