### ISSUE TITLE
Costmetic upgrade to the example project

### ISSUE THREAD

**Issue by rossabaker** [scalatra/scalatra#217]
The example project has grown a great number of servlets over the years, which has added a lot to the footer menu, which now looks horrendous.  Looks are important in first impressions -- would be great to clean this up.

**Comment by magnolia-k** [comment]
Scalatra examples are currently collected in the following repositories, and should be discussed in the following repositories if further improvement is needed.

https://github.com/scalatra/scalatra-website-examples
