### ISSUE TITLE
custom JSON renderer does not work if class in not a case class

### ISSUE THREAD

**Issue by kgignatyev** [scalatra/scalatra#306]
if I register my serializer/deserializer like this

``` scala
protected implicit val jsonFormats: Formats =    org.json4s.DefaultFormats  + new MotorcyclePreferenceSerializer

class MotorcyclePreferenceSerializer
        extends CustomSerializer[MotorcyclePreferences](
        format =>({
          case v:JString=>{
             MotorcyclePreferences.fromString( v.toString)
          }
}, {
  case d: MotorcyclePreferences =>{
    JString(MotorcyclePreferences.toString( d ))
  }
})){

}
```

it does not work till I make MotorcyclePreferences a case class. That does not quite make sense.

As far as I can tell it is caused by org.scalatra.json.JValueResult#renderToJson method that does not call Extraction.decompose(p) if p is not kind of Product.

It would be better if custom serialize/deserializer take precedence over defaults.

**Comment by gursahibexp** [comment]
is this fixed?
