### ISSUE TITLE
SwaggerBase.renderIndex() should sort services by their resource path

### ISSUE THREAD

**Issue by swartzrock** [scalatra/scalatra#313]
Currently SwaggerBase.renderIndex() displays services in the order that they are returned from the hashmap. Instead this method should sort the list of API's by their resourcePath field so they appear sorted in the api-docs json service, and thus in the swagger docs which load them.

**Comment by magnolia-k** [comment]
This problem seems to be resolved because the current implementation sorts by the return value of the 'operation' method.

Please create a new issue if you have any other issues.
