### ISSUE TITLE
Mounting differences between ScalatraSuite and ServletContext

### ISSUE THREAD

**Issue by Woodz** [scalatra/scalatra#317]
ServletContext.mount(MyServlet, "/test/") forwards requests for "/test" and "/test/", whereas in ScalatraSuite.mount(MyServlet, "/test/") only forwards requests for "/test/", and returns 404 for "/test"

**Comment by magnolia-k** [comment]
As of now (Scalatra 2.7.1), mount is not supported in this format, so close it.
