### ISSUE TITLE
contentType = null reverts default character set

### ISSUE THREAD

**Issue by rossabaker** [scalatra/scalatra#318]
`contentType = null` appears in the g8 template.  It unsets the response's character encoding, which means we lose the Scalatra-wide default of UTF-8.  That's surprising behavior.

**Comment by seveniruby** [comment]
it's still exist in 2.5.1

**Comment by magnolia-k** [comment]
With the following commit, contentType never gets set null

https://github.com/scalatra/scalatra.g8/commit/563dbcd4ab909cdfd2baa23c48f0b0df5d287dfd#diff-be6b9b7e103eade88b8c25f14fd4dee0
