### ISSUE TITLE
Commands, use of defaults impractical

### ISSUE THREAD

**Issue by mdedetrich** [scalatra/scalatra#337]
The use of defaults in commands is incredibly annoying, and it has caused me to redundantly have to a put a validation layer ontop of commands as well as never being able to use `asType` for anything thats not a string

There are 2 situations here, one is when the field is required and one where the field isn't required

If the field isn't required, than its not an issue because the `.required` will suppress any conversion should the field be invalid

The other case is if the field is optional (i.e. not required). What currently happens is that when a field is missing, it will get replaced by a default value (0 for ints, longs, "" for strings, etc etc). The problem is, there is no way to suppress this behavior, and there are plenty of use cases where using `defaultValues` breaks business logic.

For example, if you have a field that is a "length of time" which has `asType[Long]`, this will use 0 as a defaultValue. 0 is however a legitimate value for length of time, however you may wan't the user to forcibly provide that 0, instead of just assuming the length of time is 0 without any user input

**Proposal**
Default values should not be enabled by default (or if they should remain as default, there should be a method that supress default values, however I believe the former makes more design sense and practical sense, I can't see any use case for default values as this stuff is mostly handled client side)

If the field is required, than it will default to a None (instead of the default value) should a non sensible input be provide. However if the field is optional, than it will default to None (if the field is missing or non sensible). In order to use default values, you have to add something like a `.useDefault()` method onto the `Field` declaration.

@casualjim this is directed at you since you maintain the library

**Comment by magnolia-k** [comment]
scalatra-commands is removed from library at 2.7.x.
