### ISSUE TITLE
Cannot get path parameters in atmosphere route using params("key") due to NPE in ScalatraBase

### ISSUE THREAD

**Issue by wkozaczuk** [scalatra/scalatra#380]
When calling params("id") in atmosphere route it fails with org.scalatra.ScalatraException: An atmosphere route should return an atmosphere client that is triggered by NPE on line 767 in ScalatraBase:multiparams() method.

The route looks like that:

  atmosphere("/jobStatuses/:jobGuid") {
    new JobStatusUpdateAtmosphereClient(params("jobGuid"))
  }

During debugging I notices that the parameter jobGuid get parsed out during route matching logic and placed in HttpServletRequest object. However later when constructing JobStatusUpdateAtmosphereClient and calling params() the request:HttpServletRequest is null in ScalatraBase:multiparams() method. Is there any other way to get to the path parameters? Or is it simply not supported

**Comment by lightvector** [comment]
Is there any workaround to this?

**Comment by lightvector** [comment]
Ah, looks like this is fixed already in 2.4.0-RC2-2. Can this issue be closed then?
