### ISSUE TITLE
Scalatra tests throw exception with scalatra-scalatest_2.10-2.2.2

### ISSUE THREAD

**Issue by itryapitsin** [scalatra/scalatra#381]
Scalatra test throw exception 
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null

My pom.xml contains 
<dependency>
                <groupId>org.scalatra</groupId>
                <artifactId>scalatra_2.10</artifactId>
                <version>2.2.2</version>
            </dependency>
            <dependency>
                <groupId>org.scalatest</groupId>
                <artifactId>scalatest_2.10</artifactId>
                <version>2.0</version>
            </dependency>
            <dependency>
                <groupId>org.specs2</groupId>
                <artifactId>specs2_2.10</artifactId>
                <version>2.3.10</version>
            </dependency>

**Comment by magnolia-k** [comment]
ScalaTest has also been upgraded, and since there have been no more of the same issues, it is closed.
