### ISSUE TITLE
NotFound() returns 200 instead of 404

### ISSUE THREAD

**Issue by ceedubs** [scalatra/scalatra#390]
In an action, returning `NotFound("foo")` gives a 404 response as I would expect. However returning `NotFound()` (which defaults to `Unit` as a body) returns a 200 response status, which doesn't seem right.

It seems that [this](https://github.com/scalatra/scalatra/blob/2.3.0.RC1/core/src/main/scala/org/scalatra/ScalatraBase.scala#L445-446) may be relevant code, but I'm having trouble tracing the logic through the layers.

This is on 2.3.0.RC1.

**Comment by orlandojsjr** [comment]
@ceedubs the problem was discovered by @verto. You can see here https://github.com/scalatra/scalatra/issues/554
