### ISSUE TITLE
Scalate :coffeescript filter doesn't work without explicit RhinoCoffeeScript dependency

### ISSUE THREAD

**Issue by DavidHosking** [scalatra/scalatra#398]
While trying to use [xsbt-wro4j-plugin](https://github.com/BowlingX/xsbt-wro4j-plugin/) I was unable to have my Coffeescript complied on the server side (using an in-line jade filter: ":coffeescript").

The result was the coffeescript being inserted directly into output inside <script type "text/coffeescript"> tags.

[org.fusesource.scalate.filter.CoffeeScriptFilter](https://github.com/scalate/scalate/blob/scala_2.10/scalate-core/src/main/scala/org/fusesource/scalate/filter/CoffeeScriptFilter.scala) generated a "No Rhino on the classpath:" error.

I have been able to fix this by adding ["ro.isdc.wro4j" % "wro4j-core" % "1.7.5"](http://mvnrepository.com/artifact/ro.isdc.wro4j/wro4j-core/1.7.5) and ["ro.isdc.wro4j" % "wro4j-extensions" % "1.7.5"](http://mvnrepository.com/artifact/ro.isdc.wro4j/wro4j-extensions/1.7.5) to my list of dependencies.

I am unsure weather this is the correct solution, or if I am missing something.

If there isn't some deeper problem that I'm not seeing, then perhaps it should be noted that these dependencies are necessary on the [coffeescript page](http://www.scalatra.org/2.2/guides/resources/coffeescript.html) and maybe even the [wro4j page](http://www.scalatra.org/2.2/guides/resources/wro4j.html).

**Comment by DavidHosking** [comment]
Hi.  Apologies for taking so long to respond.

Thanks @BowlingX, that cleared up some confusion for me.

Scalate still needs a Rhino dependency to be present in build.scala.  Currently this seems to be ["tv.cntt" % "rhinocoffeescript" % "1.9.0"](http://mvnrepository.com/artifact/tv.cntt/rhinocoffeescript/1.9.0) ([GitHub](https://github.com/xitrum-framework/RhinoCoffeeScript)).

I'm not entirely sure why the dependency has changed (or if it really has, since my build environment has changed), however the wro4j dependencies no longer work for this problem.

**Comment by magnolia-k** [comment]
The xsbt-wro4j-plugin is no longer being developed, so this issue is closed.
