### ISSUE TITLE
Make error page rendering configurable through system properties

### ISSUE THREAD

**Issue by casualjim** [scalatra/scalatra#405]
Currently there is no way to reconfigure a scalatra application to not use scalate error page rendering without recompiling.  This could be using a system property and/or env variable

**Comment by jamesfe** [comment]
@seratch I could work on this.  Can you point me to the source code where it happens?

**Comment by magnolia-k** [comment]
Scalate is strongly dependent on the internal structure of the Scala compiler, so a major version upgrade is currently on hold.

There are plans to remove the dependency on Scalate from Scalatra in the future, and issues that require additional Scalate functionality may be closed.
