### ISSUE TITLE
Scalatra Swagger not working correctly

### ISSUE THREAD

**Issue by nidkil** [scalatra/scalatra#437]
Hi,

I have pulled the Scalatra examples from Github (https://github.com/scalatra/scalatra-website-examples). I tried running the Swagger example for version 2.3. The example runs, but the API documentation is not generated completely. I am using the example as is. When I call http://localhost:8080/api-docs in the browser I get the following result:

```
{"apiVersion":"1","swaggerVersion":"1.2","apis":[{"path":"/flowers","description":"The flowershop API. It exposes operations for browsing and searching lists of flowers"}],"authorizations":{},"info":{"title":"The Flowershop API","description":"Docs for the Flowers API","termsOfServiceUrl":"http://scalatra.org","contact":"apiteam@scalatra.org","license":"MIT","licenseUrl":"http://opensource.org/licenses/MIT"}}
```

I also dubbel checked if the 2.2 version works, but it generates even less:

```
{"basePath":"http://localhost:8080","swaggerVersion":"1.0","apiVersion":"1","apis":[{"path":"/api-docs/flowers.{format}","description":"The flowershop API. It exposes operations for browsing and searching lists of flowers"}]}
```

Any suggestions why swagger is not working correctly?

Regards, nidkil

**Comment by futurechimp** [comment]
Hi @nidkil, 

Sorry to take so long with this. 

The guide needed to be updated, I've now corrected it. The correct URL for a Swaggerized Scalatra 2.3.0 application is http://localhost:8080/api-docs.

**Comment by davidjones7076** [comment]
Using 2.3.0 at http://localhost:8080/api-docs I get the the following JSON.

Any ideas why I don't get a basePath value returned ?

{"apiVersion":"1.0.0","swaggerVersion":"1.2","apis":[{"path":"/flowers","description":"The flowershop API. It exposes operations for browsing and searching lists of flowers, and retrieving single flowers."}],"authorizations":{},"info":{}}

**Comment by vsporeddyexp** [comment]
@davidjones7076, I'm having the same issue. Have you resolved it?

**Comment by ronaldo-getreveel** [comment]
Any update? Using scalatra-swagger 2.4.0.RC3 and it doesn' t work.

**Comment by razem-io** [comment]
Sorry to ask again but I ran into the same issue. Swagger makes no sense when this does not work. Anyone knows how to fix this? Thank you in advance.

**Comment by razem-io** [comment]
Ok. I got it working! Problem was I used a generated server project based on a swagger yml. It had many old dependencies which resulted in this behaviour. I ended up refactoring based on the following example: https://github.com/scalatra/scalatra-website-examples/tree/master/2.4/swagger-example

Now everything works as expected!
