### ISSUE TITLE
Serving text/plain content as an array of bytes is extremely slow

### ISSUE THREAD

**Issue by leifwickland** [scalatra/scalatra#459]
When `serving text/plain; charset=utf-8` content as an array of bytes which has already been encoded in the target character set, Scalatra is extremely slow. For example, a half megabyte of static contetn takes about 4 minutes to serve on my box. 

Profiling reveals that the slowdown occurs in `org.scalatra.util.FileCharset.apply()`.

I created a [git repo](https://github.com/leifwickland/scalatra-chardet-issue.git) to make the problem easy to reproduce.

The repo's [servlet](https://github.com/leifwickland/scalatra-chardet-issue/blob/master/src/main/scala/com/example/app/MyScalatraServlet.scala#L24) is essentially doing just this:

```scala
    val utf8Body = ("x" * length).getBytes("UTF-8")
    val contentTypeHeader = Map("Content-Type" -> "text/plain; charset=utf-8")
    Ok(utf8Body, contentTypeHeader)
```

The problem exists for any `text/*` Content-Type.

The problem can be worked around by returned returning the body as a `String` instead of `Array[Byte]`.

## Steps to Reproduce

```sh
$ git clone https://github.com/leifwickland/scalatra-chardet-issue.git
$ cd scalatra-chardet-issue
$ ./sbt
> container:start
> time curl http://localhost:8080/1 >/dev/null
# Serves content snappily
> time curl http://localhost:8080/500000 >/dev/null
# Wait patiently. It takes about four minute to serve a half megabyte of static content on my box
```

**Comment by takezoe** [comment]
Already fixed in #500
