### ISSUE TITLE
Route path params not available for route conditions

### ISSUE THREAD

**Issue by DavidHosking** [scalatra/scalatra#475]
When trying to use conditional route matchers for routes with path parameters, trying to use the path param in a Boolean RouteMatcher generates a java.util.NoSuchElementException.

For example:
```
get("/:key", params("key") == "waffle") {
  "Have a " + params("key") + "!"
}
```
For a request of "http://localhost:8080/waffle" this generates `java.util.NoSuchElementException: key not found: key`.

However,  a request of "http://localhost:8080/waffle?key=waffle" generates `Have a waffle!`.

Also "http://localhost:8080/toast?key=waffle" gives `Have a toast!`, and "http://localhost:8080/waffle?key=toast" does not match.

Is this intended behavior?

**Comment by rossabaker** [comment]
Yes.  This has been argued both ways in the past, but it settled like this.  There is no implied sequencing of route matchers, and there is a very modest runtime gain.

```scala
get("/:key") {
  if (params("key") != "waffle") pass
  s"Have a ${params("key")}!"
}
```

**Comment by DavidHosking** [comment]
Okay, thank you.
