### ISSUE TITLE
Swagger 2.0 support

### ISSUE THREAD

**Issue by rossabaker** [scalatra/scalatra#495]
We currently generate Swagger 1.2.  I suddenly have a need for Swagger 2.0, and it has been asked for by several users, including in #489.  I'm going to see if I can make this happen.

I will either have a pull request very soon, or bump this to 2.5.

**Comment by seratch** [comment]
@rossabaker Any updates?

**Comment by rossabaker** [comment]
The swagger-core library is still at a milestone, which means reimplementing a bunch of things by hand. I think this should wait for 2.5.

**Comment by seratch** [comment]
I see. Thanks. I'll move this issue to 2.5 milestone.

**Comment by webron** [comment]
We just release a final non-milestone version of swagger-core with 2.0 support. I'm also reorganizing the list of tools/libraries that support 2.0, so hope to get updates here on when I can put Scalatra back up on the list of Swagger 2.0 libraries.

**Comment by MLnick** [comment]
@rossabaker would be really great to see Swagger 2.0 support in Scalatra - I really need to use the new support for object models (ie `Map[String, Any]` type of model attributes)

**Comment by rossabaker** [comment]
I'm hoping to have a meeting this week with the Swagger folks to discuss the Scala support.  Hopefully something coming soon here.

**Comment by MLnick** [comment]
@rossabaker any update? :)

**Comment by rossabaker** [comment]
Our Swagger upgrade at work got delayed, which meant my time to work on this got delayed.  It's still on my radar, but I don't have a timeline at the moment.

**Comment by hugolima88** [comment]
+1 to this feature.

**Comment by carueda** [comment]
Any updates on this?

I've been a happy Scalatra user for years (on on various projects) ... but Scalatra development seems to have slowed down for a good while already .. not a good sign ; /

In any case, thanks much guys for all your efforts.
