### ISSUE TITLE
Rendering JNull in a servlet

### ISSUE THREAD

**Issue by Pyppe** [scalatra/scalatra#496]
Rendering `JNull` in a servlet yields an empty response. I think this is caused by the `JValueResult`'s `def renderToJson: RenderPipeline` (see https://github.com/scalatra/scalatra/blob/49e794963668876aa3dc3b3c489c190ec21e8547/json/src/main/scala/org/scalatra/json/JValueResult.scala#L21)

IMO the correct behavior would be to handle `JNull` the same way as any `JValue`, which would yield in a response of `null`. See the JSON specification: https://tools.ietf.org/html/rfc7159#section-2

For example, jQuery handles an empty content with content-type `application/json` as an error.

**Comment by seratch** [comment]
I agree. Would you please make a pull request to fix this?

**Comment by Pyppe** [comment]
You beat me to the bunch. Well done, Sir! :+1:
