### ISSUE TITLE
Error when "extends ScalatraSpec with JacksonJsonSupport"

### ISSUE THREAD

**Issue by yormi** [scalatra/scalatra#497]
Hi folks !

I'm not sure if it's the right place to submit this issue but here we go !

When I want to extend both ScalatraSpec and JacksonJsonSupport, I get this output.

> [error] /home/guillaume/Documents/LiU/TDDD27/slackportal/src/test/scala/slackportal/EventServiceSpec.scala:16: overriding method contextPath in trait EmbeddedJettyContainer of type => String;
[error]  method contextPath in trait ScalatraBase of type => String has weaker access privileges; it should be public;
[error]  other members with override errors are: response, status
[error] class EventServiceSpec extends ScalatraSpec with Mockito with JacksonJsonSupport with JsonConverter { def is = s2"""

Just ask if you need more info !

    sbt.version=0.13.5

```scala
val ScalaVersion = "2.11.1"
val ScalatraVersion = "2.3.0"

libraryDependencies ++= Seq(
        "org.scalatra" %% "scalatra" % ScalatraVersion,
        "org.scalatra" %% "scalatra-scalate" % ScalatraVersion,
        "org.scalatra" %% "scalatra-specs2" % ScalatraVersion % "test",
        "ch.qos.logback" % "logback-classic" % "1.1.2" % "runtime",
        "org.eclipse.jetty" % "jetty-webapp" % "9.1.5.v20140505" % "container;provided",
        "org.eclipse.jetty" % "jetty-plus" % "9.1.5.v20140505" % "container",
        "javax.servlet" % "javax.servlet-api" % "3.1.0",
	"org.scalatra" %% "scalatra-json" % "2.3.0",
	"org.json4s" %% "json4s-jackson" % "3.2.10",
	"org.mongodb" %% "casbah" % "2.7.2",
	"org.json4s" %% "json4s-mongo" % "3.2.10"
),```

**Comment by seratch** [comment]
We cannot help you without seeing your `EventServiceSpec.scala`. 

Anyway, please post questions to [Google Group](https://groups.google.com/forum/#!forum/scalatra-user) or http://stackoverflow.com/. see also: http://scalatra.org/community/index.html
