### ISSUE TITLE
The website doesn't work the documentation is down

### ISSUE THREAD

**Issue by mrkaspa** [scalatra/scalatra#498]
Try going http://www.scalatra.org/ and get nothing

**Comment by rossabaker** [comment]
Is this still an issue? It works for me.

**Comment by mrkaspa** [comment]
I think is my ISP it has the IP Blocked really weird

**Comment by seratch** [comment]
@mrkaspa Is it fine now? If there is nothing we can do on this now, we'd like to close this issue.

**Comment by rossabaker** [comment]
We transferred the domain around the time the issue was opened, but I
observed no downtime and still don't.

**Comment by takezoe** [comment]
The web site has been  moved to GitHub Pages and hugo. It's now stable.
