### ISSUE TITLE
Extra space in http headers causes 400

### ISSUE THREAD

**Issue by jimmyhmiller** [scalatra/scalatra#499]
If you have a header with a extra space after the colon you get the following error:

```
HTTP/1.1 400 Bad EOL
Connection: close
Content-Length: 0
Server: Jetty(9.1.5.v20140505)
```

Here is what was sent:

```
GET / HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:9000
User-Agent: HTTPie/0.8.0
test:   test
```

**Comment by seratch** [comment]
Simply running the HTTP request doesn't reproduce your situation. Please let us know Scalatra example code to reproduce your issue.

**Comment by magnolia-k** [comment]
This issue is then closed because the required information has not been reported.
