### ISSUE TITLE
Stable request reference but unstable attributes

### ISSUE THREAD

**Issue by lloydmeta** [scalatra/scalatra#513]
When using `AsyncResult`, it seems to me that even though `request` and `responses` are stable, the referenced data itself is unstable when called asynchronously from code executing in other threads. For example, until the current thread gives up control to another thread `request#getContextPath` is stable, but returns "null" (!) otherwise.

e.g. 

```scala
...
get("path"){
  request.getContextPath // => returns context path
  new AsyncResult {
    request.getContextPath // => still returns context path
    val is = Future {
      request.getContextPath // => null here
    }
  }
}
```

I'm not entirely sure how this can be resolved or what the root cause is (maybe it's caused when the Servlet container tries to recycle the request object when the original HTTP handler thread returns and references get wiped out), but maybe doing a clone [here](https://github.com/scalatra/scalatra/blob/402256990b82230905570b1924a3a827a6fbce20/core/src/main/scala/org/scalatra/ScalatraContext.scala#L71) would help?

**Comment by dozed** [comment]
You probably mean `AsyncResult`. Are you sure you are returning the `AsyncResult` from the action? I tried to reproduce your use case and it worked for me:

```scala
get("/request-context-path") {
  request.getContextPath // => returns context path

  new AsyncResult {
    val is = Future {
      val a = request.getContextPath // => returns context path
    }
  }
}
```

What you might experience is, that the request/response is invalidated by Jetty. Returning an AsyncResult/Future puts the request into asynchronous mode and the request/response objects (and all attributes) are valid until the Future completes, which marks the end of the HTTP request/response cycle.

What currently does not work is, when you try to access the request/response without the asynchronous synchronization, for example when side-effecting:

```scala
get("/request-context-path") {

  Future {
    // do side-effecting, e.g. send email

    request.getContextPath   // getContextPath, getSession etc. might fail, since the request/response are invalidated by Jetty
  }

  Ok()
}
```

Also note that we are working on removing the need to explicitely define an `AsyncResult` (https://github.com/scalatra/scalatra/pull/511).

**Comment by lloydmeta** [comment]
> You probably mean AsyncResult. Are you sure you are returning the AsyncResult from the action? I tried to reproduce your use case and it worked for me

Sorry, you're right, it's `AsyncResult`. I'm fairly certain that in your example, if you check, you will have an empty body, but do not be fooled, it is empty not because you have no context for your servlet, it is empty because `getContextPath` is actually `null` and Jetty/Scalatra (doesn't matter) thinks that means no body to do vestiges of the "Java" way. Try doing `s"${request.getContextPath}` and you will likely see that the string is null.

> Can you post a failing test case?

See #514 for a failing test case (demonstrating exactly what I explained) and proposed fix.

**Comment by dozed** [comment]
This test passes for me, can you try it please?

```scala
package org.scalatra

import _root_.akka.actor.ActorSystem
import org.scalatra.test.specs2.MutableScalatraSpec

import scala.concurrent.{ExecutionContext, Future}
import scala.concurrent.duration._

class AsyncSpec extends MutableScalatraSpec {
  sequential

  addServlet(new ScalatraServlet with FutureSupport {
    // protected implicit val executor = scala.concurrent.ExecutionContext.global
    lazy val system = ActorSystem()
    override protected implicit val executor: ExecutionContext = system.dispatcher
    override def asyncTimeout = 2 seconds

    get("/async-oh-noes") {
      new AsyncResult {
        override val is = Future {
          Ok(body = s"${request.getContextPath}")
        }
      }
    }

    override def destroy() {
      super.destroy()
      system.shutdown()
    }


  }, "/*")


  "have a stable request" in {
    get("/async-oh-noes") {
      body must_== ""
      // body must not be_== "null"
    }
  }
}
```

**Comment by lloydmeta** [comment]
@dozed the problem occurred more readily for me at work because my machine was slower and here at home, the test case I wrote (and yours) both pass: this is because due to different machine specs/circumstances, the race condition of Jetty recycling the request object before the Future ExecutionContext has picked up and executed the Future is hard to trigger without some kind of pause.

If you put a `Thread.sleep(1000)` in your future (before `Ok`), you will likely see it happen.

I've updated #514 [as well](https://github.com/lloydmeta/scalatra/commit/eb6f80c894d44b6bae520495cdf523a956608816) to make it more triggerable.

**Comment by dozed** [comment]
Yes, you are right. So the problem is that the request is mutable and being changed when falling back through Jetty's request handling chain, while the async handler keeps working with the request. We should provide the async handler (and also maybe the Scalatra action) a stable request/response, as you proposed already. Are there more attributes which are affected of this, or is `contextPath` the only one?

**Comment by lloydmeta** [comment]
> Are there more attributes affected of this, or is contextPath the only one?

I'm unsure. So far I've only had to use `contextPath`.

> We should provide the async handler (and also maybe the Scalatra action) a stable request/response, as you proposed already

The real question is how. Spray already does this by providing an immutable Request to the developer (and to be honest, the DSL is already close enough to Scalatra and it's compatible with Servlets via spray-servlet). In #514 I've proposed a kind of manual copying into another `HttpRequest`. Perhaps this discussion should now be moved to #514 instead.

**Comment by rossabaker** [comment]
The context path might be available in a [horrible, awful request attribute](http://docs.oracle.com/javaee/6/api/javax/servlet/AsyncContext.html#ASYNC_CONTEXT_PATH).  I have observed different servlet containers behaving differently on the same code, but if a request value has suddenly disappeared, it may be tucked away in that request context.

I wonder if it might help to redefine our own helpers to fall back to these request attributes on an unexpected null.

**Comment by lloydmeta** [comment]
@rossabaker I gave your suggestion a try, but either I misunderstood what you're talking about or it's not so easy because when I need to get a handle on the async request context, it doesn't exist yet. Please see #514 for further discussion.

PS: I love the idea of making Scalatra 3.0 depend on HTTP4S to achieve immutable Request/Responses because it's more idiomatic and opens up the doors to using non-blocking I/O w/ Scalatra.

**Comment by lloydmeta** [comment]
Closing because #514 was merged.
