### ISSUE TITLE
Future support fails with high throughput

### ISSUE THREAD

**Issue by janstenpickle** [scalatra/scalatra#515]
First time I've reported an issue here so just wanted to say I love the project, and keep up the good work!

One of my colleagues and I have been looking into a strange issue with the Scalatra future support when we were testing with scalacheck, basically we run into concurrency problems and manage to deadlock the process, or run into `java.nio.channels.ReadPendingException`s.

I've managed to recreate the issue complete with travis builds in this repo here: https://github.com/janstenpickle/scalatra-future-support-test. 

I'm getting a bit lost in the future support code, so I was wondering if one of the core devs could have a look and shed some light on the problem, it's likely that it's something I'm doing wrong!

**Comment by rossabaker** [comment]
The request and response are stored in a DynamicVariable, which is thread
scoped.  When you reference the request or response directly in a Future,
you're on a different thread.  (This is similar to the problem of closing
over `sender` if you use Akka.)  Ways around this are:

1) Get what you need off the request synchronously, and pass that into your
Future code.
2) Use an AsyncResult:
http://www.scalatra.org/2.3/guides/async/akka.html#toc_151

AsyncResult is the safer, but ugly, approach to async.  Stefan has a
solution in https://github.com/scalatra/scalatra/pull/511 that I believe
would make your specs pass in their current form.  We're just knocking some
rough edges off that, but I expect that will land soon.

**Comment by janstenpickle** [comment]
Thanks for the help! I'll look into doing this with an AsyncResult.
