### ISSUE TITLE
Test failed on Travis

### ISSUE THREAD

**Issue by dozed** [scalatra/scalatra#523]
See: https://travis-ci.org/scalatra/scalatra/jobs/66744897

```
[info] GetResponseStatusSupportTest:
[info] - remember status after setStatus
[info] - remembers status after sendRedirect
[info] - remembers status after sendError without a message *** FAILED ***
[info]   "[none]" did not equal "[500]" (GetResponseStatusSupportTest.scala:55)
[info] - remembers status after sendError with a message
```

Usually this test passes. Is this some kind of race condition?

**Comment by seratch** [comment]
Yeah, I think so too. Just introducing a small sleep will improve that. https://github.com/scalatra/scalatra/blob/2.4.x/core/src/test/scala/org/scalatra/GetResponseStatusSupportTest.scala

**Comment by rossabaker** [comment]
I wonder why that's a race.  That second get shouldn't be issued until the first request is complete, should it?

**Comment by magnolia-k** [comment]
Now that the tests on Travis are working correctly, this issue will be closed.
