### ISSUE TITLE
Not a valid command: aux-compile

### ISSUE THREAD

**Issue by pjb3** [scalatra/scalatra#532]
The instructions here: http://scalatra.org/2.4/getting-started/first-project.html

Say to get automatic code reloading to work, to run this:

```
$ ./sbt
> container:start
> ~ ;copy-resources;aux-compile
```

But when I do that, I get this error:

```
[error] Not a valid command: aux-compile
[error] Not a valid project ID: aux-compile
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: aux-compile (similar: compile, compilers, on-complete)
[error] aux-compile
[error]
```

I just followed the getting started instructions to get going, so I believe I'm using the latest version of things, which are Scala 2.11.6, ScalatraVersion 2.4.0-RC2-2, sbt 0.13.8

**Comment by rossabaker** [comment]
Thanks.  You can now use `~container:start`.  See scalatra/scalatra-website#100.  We had an issue with the CI server that publishes the site, but it will be correct on scalatra.org soon.
