### ISSUE TITLE
A redirect throws org.scalatra.HaltException within a try-catch block

### ISSUE THREAD

**Issue by kmels** [scalatra/scalatra#539]
```
get("/error") {
    try {
      redirect("https://github.com/scalatra/scalatra")
    } catch {
      case e: Throwable => {
        e.printStackTrace()
        redirect("http://google.com")
      }
    }
  }
```

GET /error should redirect to https://github.com/scalatra/scalatra but redirects to http://google.com instead

**Comment by rossabaker** [comment]
redirect and halt are implemented by throwing a control exception, so thst subsequent side effects don't run.  You can avoid this by catching `case NonFatal(e) =>`

**Comment by kmels** [comment]
Thanks for the explanation, is there a way to delegate `case NonFatal(s)` or the HaltException to scalatra so that it could reply with the redirect?
