### ISSUE TITLE
Java 1.6

### ISSUE THREAD

**Issue by yglushonkova** [scalatra/scalatra#547]
Hi
In our project we use scalatra 2.3.1 but we need to support java 1.6 still.
Is it possible to support Java 1.6 ?

**Comment by seratch** [comment]
Since 2.3.0, Scalatra supports servlet 3.1 or higher that require JDK 1.7 or higher. So unfortunately it's not possible to support JDK 1.6 in 2.3.x series.

**Comment by yglushonkova** [comment]
Thank you!
