### ISSUE TITLE
issues with json

### ISSUE THREAD

**Issue by jsolack** [scalatra/scalatra#548]
There appears to be some issues with json and the scalatra 2.4.  see the following thread:

https://groups.google.com/forum/#!topic/scalatra-user/V0dS46b-jfU

**Comment by seratch** [comment]
Hi Kaz,

I just tried Scalatra 2.4.0.RC3 with json4s-jackson 3.3.0 and everything is working fine.

```
  val ScalatraVersion = "2.4.0.RC3"

      libraryDependencies ++= Seq(

        "org.scalatra" %% "scalatra" % ScalatraVersion,
        "org.scalatra" %% "scalatra-scalate" % ScalatraVersion,
        "org.scalatra" %% "scalatra-specs2" % ScalatraVersion % "test",

        "org.scalatra" %% "scalatra-json" % ScalatraVersion,
        "org.json4s" %% "json4s-jackson" % "3.3.0",
```

Thanks,
-Khoi
- hide quoted text -


On Tuesday, November 24, 2015 at 7:51:53 PM UTC-6, Kazuhiro Sera wrote:
Sandro, 
Khoi,

scalatra-json 2.4.0.RC3 is compatible with not json4s 3.3.0.RC* but json4s 3.3.0.

I believe using 2.4.0.RC3 with json4s 3.3.0 should work fine. Would you try it out when you have time?

-Kaz
