### ISSUE TITLE
Activator?

### ISSUE THREAD

**Issue by nlhkh** [scalatra/scalatra#551]
A common way to start a Scala application is with Activator. It seems that there is no official template for Scalatra in Activator yet.

**Comment by seratch** [comment]
We already have a gitter8 template to build a blank project. https://github.com/scalatra/scalatra-sbt.g8
It may be fine to create an activator template if someone'd love to keep maintaining it

**Comment by xuwei-k** [comment]
http://www.lightbend.com/community/core-tools/activator-and-sbt
