### ISSUE TITLE
error handler does not handle exception in Futures

### ISSUE THREAD

**Issue by ElPicador** [scalatra/scalatra#569]
I have a strange error when using `FutureSupport` and `error` handling. 

If an exception is throwned in a `Future` the `error` handler is called but not used.

See: https://gist.github.com/ElPicador/b9b7dd0111e3ecb7b6f3
Calling `/sync`, `/future` works.
Calling `/sync_fail` renders the `halt` in the `error` handler
Calling `/future_fail` calls the `halt` in the `error` handler, but the output is raw text displaying : org.scalatra.HaltException, see https://www.dropbox.com/s/gj20n4ihnn9tybd/Capture%20d%27%C3%A9cran%202016-03-21%2018.02.20.png?dl=0

**Comment by rossabaker** [comment]
Fixed by #572
