### ISSUE TITLE
Returning files >2GB get truncated at size Integer.MAX_VALUE

### ISSUE THREAD

**Issue by pmcq** [scalatra/scalatra#575]
From a simple scalatra application trying to serve files, files larger than 2GB get truncated at Integer.MAX_VALUE without any kind of warning issued etc.  This can be reproduced by simply having a controller return:
```scala
val someFile = new File(...)
Ok(someFile)
```
The cause is that JDK spec for FileChannels states it's possible not all bytes will get copied, and looking at the openJDK spec as a reference, while all the method signatures take/return longs only up to Integer.MAX_VALUE will get copied at one time:
https://docs.oracle.com/javase/8/docs/api/java/nio/channels/FileChannel.html#transferTo-long-long-java.nio.channels.WritableByteChannel-
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/sun/nio/ch/FileChannelImpl.java#550

**Comment by gregw** [comment]
The most efficient way to server a large files on the Jetty server is to use a file mapped buffer and an asynchronous write. This will write the file with minimum copying (perhaps none) and no thread waiting for it it complete.

If you want jetty specific code for this, please @ me and I'll provide some more examples.
