### ISSUE TITLE
Latest Atmosphere version support / Atmosphere example problem

### ISSUE THREAD

**Issue by fangqiao** [scalatra/scalatra#582]
I am all new to Scalatra. Just get it up and running.

I cloned and compiled your example for Atmosphere(/2.4/async/scalatra-atmosphere-example).

It complained that Atmosphere was 2.0.3 while that latest is 2.4.5. The front end js reported that is wrong version (2.0.3). Backend and front end refused to talk.

I mannually downloaded the latest Atmosphere javascript library and put them to the example's javascript folder. It worked.

I recommend you guys update your scalatra-atmosphere lib for the latest version of atmosphere and also update your example's javascript library.

Cheers,

**Comment by magnolia-k** [comment]
They are all aligned to the new version now.

I'm sorry for the very slow response, please report any other problems!
