### ISSUE TITLE
Install giter8 command on website is out of date: n8han/giter8

### ISSUE THREAD

**Issue by maxipesfix** [scalatra/scalatra#584]
cs n8han/giter8 ==> cs foundweekends/giter8

**Comment by futurechimp** [comment]
Hi @maxipesfix, I'm not seeing the `n8han` repo mentioned anywhere on the website. Can you point to a specific URL?

**Comment by magnolia-k** [comment]
Scalatra's Website has already been repaired.

http://scalatra.org/getting-started/installation.html
