### ISSUE TITLE
PUT request - Key id could not be found

### ISSUE THREAD

**Issue by orlandojsjr** [scalatra/scalatra#588]
I'm making a PUT request with 'id' attribute in the body. I got the following error:

``` scala
 put("/resource") {
    params.as[Long]("id") // EXCEPTION - Key id could not be found
 }
```

Not working:
`curl -X PUT -d id=2 host.com/resource`

Works fine:
`curl -X POST -d id=2 -d _method=put host.com/resource`

**Comment by magnolia-k** [comment]
This event was not reproduced in Scalatra 2.7.1, so it is closed.
