### ISSUE TITLE
FileUploadSupport does not work with ScalatraFilter

### ISSUE THREAD

**Issue by dadepo** [scalatra/scalatra#592]
Using FileUploadSupport with ScalatraServlet works as documented here http://www.scalatra.org/guides/formats/upload.html

But once ScalatraServlet is replaced with ScalatraFilter, it stops working and when an upload is attempted, the following exception is thrown:

```
Caused by: java.lang.IllegalStateException: No multipart config for servlet
```

**Comment by takezoe** [comment]
`FileUploadSupport` does not work with `ScalatraFilter` perfectly. Documentation seems to have already been fixed.
