### ISSUE TITLE
CorsSupport is broken

### ISSUE THREAD

**Issue by jelmerk** [scalatra/scalatra#596]
Hi, I was investigating a security issue reported against our platform and discovered that this seems to be a bug in scalatra's CORSSupport

The documentation at http://www.scalatra.org/2.4/guides/web-services/cors.html
contains this entry :

> You can configure your application to be more restrictive by using the following init params.
> 
> context.initParameters("org.scalatra.cors.allowedOrigins") = "http://example.com:8080 http://foo.example.com" - List the hosts and ports which will be allowed to make cross-origin requests, separated by spaces (\* by default).

However on line 74 it becomes clear that commas are used as seperators instead of spaces

https://github.com/scalatra/scalatra/blob/2.3.x_2.10/core/src/main/scala/org/scalatra/CORSSupport.scala#L74

But more importantly, this configuration gets completely ignored when augmenting a simple request. on line 124 you can see that it will just set the value of the Access-Control-Allow-Origin header to whatever is specified in the Origin header. effecively allowing calls from any domain

https://github.com/scalatra/scalatra/blob/f4385c2b14e9a4bcf7394c82b4eecd2e0ed03fa3/core/src/main/scala/org/scalatra/CORSSupport.scala#L124

**Comment by jelmerk** [comment]
Pull request : https://github.com/scalatra/scalatra/pull/597

**Comment by seratch** [comment]
Thanks, LGTM 👍

**Comment by seratch** [comment]
Oops, the above comment is for the PR.

**Comment by andrewjackman** [comment]
The website change commits above have been merged, but the actual code fix (https://github.com/jelmerk/scalatra/commit/942f1b7aaea9e98b58118948565944e3dffecf39) has not. Any idea why? CORS is still broken because it will accept AnyOrigin even if you specify a list of origins in using context.initParameters("org.scalatra.cors.allowedOrigins") = ...
