### ISSUE TITLE
Scalatra compiled against Scala 2.12

### ISSUE THREAD

**Issue by kamilkloch** [scalatra/scalatra#600]
Is there any time horizon to release Scalatra compiled against Scala 2.12?

**Comment by takezoe** [comment]
I can't declare the release timing but Scala 2.12 support is progressing in https://github.com/scalatra/scalatra/pull/598.

**Comment by seratch** [comment]
I just published 2.5.0-RC1 libs for Scala 2.12/2.11 to the sonatype repositories. They'll be synced to the maven central within hours. 🎉

**Comment by seratch** [comment]
After waiting for feedbacks from users with the RC release, I'm willing to publish 2.5.0 final soon.

**Comment by asanderson** [comment]
Any ETA on 2.5.0? This is the final dependency that we're waiting to drop before we upgrade. ;-)

**Comment by seratch** [comment]
I think it's fine to publish libs (I can work on it this weekend) but we have tasks on the official website. Join the discussion if you're interested in contributing. https://gitter.im/scalatra/scalatra

**Comment by seratch** [comment]
2.5.0 is available. https://twitter.com/scalatra/status/800640258568122369
