### ISSUE TITLE
2.12 Documentation Missing

### ISSUE THREAD

**Issue by asevans48** [scalatra/scalatra#611]
There is a broken dependency due to an unupdated scalate generator from com.mojolly when using Scala 2.12 with Scalatra 2.4. When searching for documents for Scalatra2.5, they don't exists. I cannot figure out a replacement for the dependency and thus an installation process without one. 

Here is the missing dependency:

[warn] 	Note: Unresolved dependencies path:
[warn] 		com.mojolly.scalate:scalate-generator_2.12:0.5.0 (/home/aevans/git/DatabaseStandardsDocumenter/pgstadardskeeper/build.sbt#L10-11)
[warn] 		  +- com.simplrtek:pgstadardskeeper_2.12:0.1
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.mojolly.scalate#scalate-generator_2.12;0.5.0: not found
[error] Total time: 2 s, completed Dec 23, 2016 9:53:16 PM

**Comment by hardlianotion** [comment]
[This project](https://github.com/skinny-framework/sbt-scalate-precompiler) is the same codebase as the xsbt-scalate-generate project with an active maintainer.  It has support for scala 2.12.

**Comment by takezoe** [comment]
I sent a pull request to fix giter8 template: https://github.com/scalatra/scalatra-sbt.g8/pull/60
