### ISSUE TITLE
Rich request should use internal methods

### ISSUE THREAD

**Issue by antonkatz** [scalatra/scalatra#625]
In RichRequest.scala 
https://github.com/scalatra/scalatra/blob/2.5.x/core/src/main/scala/org/scalatra/servlet/RichRequest.scala#L202

The method uses the ```getInputStream``` of the request, where as the internal method ```inputStream``` should be used. This makes for much easier overriding.

**Comment by antonkatz** [comment]
I can provide the patch if necessary

**Comment by magnolia-k** [comment]
https://github.com/scalatra/scalatra/pull/778
