### ISSUE TITLE
swagger tags for resources

### ISSUE THREAD

**Issue by jb08** [scalatra/scalatra#626]
Does scalatra support tagging resources by the controller name? All I've seen with scalatra apps is "Default":
<img width="102" alt="screen shot 2017-02-24 at 12 57 49 pm" src="https://cloud.githubusercontent.com/assets/8146460/23316659/f460b43c-fa90-11e6-9bb6-8ce50de5d573.png">

Looking for ability to add tags to group endpoints:
<img width="333" alt="screen shot 2017-02-24 at 12 59 22 pm" src="https://cloud.githubusercontent.com/assets/8146460/23316698/1926bc3a-fa91-11e6-9edf-d88ffa7b1983.png">

**Comment by kstigen** [comment]
+1
