### ISSUE TITLE
Swagger support for operations with no response body

### ISSUE THREAD

**Issue by salceson** [scalatra/scalatra#627]
We have an endpoint for validating a JSON file. When the file is valid we return HTTP status 200 with no response body. Currently it's not possible with Scalatra's Swagger support to register properly such an operation, although according to Swagger spec, it can be done.

Current workaround was to create a marker trait `NoResponse` and register the operation with this trait as response model.

I'd suggest we add possibility to handle such situations in better way :)

Also I'd like to thank you for your awesome work on this framework, especially for my request with Swagger that was resolved in the latest release 👍 .

**Comment by takezoe** [comment]
@salceson How about `apiOperation[Unit]`?

Here is a definition example:
https://github.com/scalatra/scalatra/blob/2.5.x/swagger/src/test/scala/org/scalatra/swagger/SwaggerSpec.scala#L584
And a generated JSON:
https://github.com/scalatra/scalatra/blob/2.5.x/swagger/src/test/resources/swagger.json#L78

**Comment by salceson** [comment]
I'm sorry to take this long to response.

Yes, with `apiOperation[Unit]` it does work. I think that this needs to be better documented though. At least for me it isn't obvious that passing `Unit` type makes the operation return no response if succeeded.

**Comment by jb08** [comment]
also see swagger-ui PR into swagger-ui 3.0.7: [link](https://github.com/swagger-api/swagger-ui/issues/2881)

**Comment by jb08** [comment]
if you want more info on `Unit` type, also see [scala docs](https://www.scala-lang.org/api/current/scala/Unit.html)
