### ISSUE TITLE
About Jade (PugJS) Template

### ISSUE THREAD

**Issue by marti1125** [scalatra/scalatra#628]
Is there an example for using Jade template I trying to pass a parameter to template
p #{foo}
like the following example (expressjs)
http://www.clock.co.uk/blog/a-simple-website-in-nodejs-with-express-jade-and-stylus
If is not exist an example about it I would like to contribute with it

**Comment by magnolia-k** [comment]
Welcome to add example code.
I would like you to send PR to the following repository

https://github.com/scalatra/scalatra-website-examples
