### ISSUE TITLE
Getting 404s from the scalatra website

### ISSUE THREAD

**Issue by rogthedodge** [scalatra/scalatra#636]
Many of the pages on the website, referenced from githib, are returning 404s. For example http://www.scalatra.org/2.5/getting-started/first-project.html

**Comment by justbaker** [comment]
+1 Same. Links on website are also broken.

**Comment by takezoe** [comment]
scalatra.org is under maintenance. I'm publishing a next hugo version of the web site of Scalatra to my GitHub Pages temporary, so you can look here if necessary.
https://takezoe.github.io/scalatra-website/

**Comment by zevektor** [comment]
I find quite unprofessional that I need to reach your github issue tracker to find out that the website is not working. Not even a little warning on your homepage?

**Comment by riccardocorbella** [comment]
I totally agree with zevektor.

**Comment by dozed** [comment]
The site builds now with Travis CI from that project https://github.com/scalatra/scalatra-docbuild.

A preview is being developed here: https://scalatra.github.io/scalatra-docbuild/

Any feedback is welcome. You can also send pull requests.

**Comment by aadrian** [comment]
@dozed it looks good, and URLs seem fixed. Can it be deployed to https://scalatra.org ?

**Comment by dozed** [comment]
The domain now points to the Github Pages site, https://github.com/scalatra/scalatra-website/tree/feature/hugo.
Please check if you find any other issues.
