### ISSUE TITLE
unable to declare endpoints as deprecated in swagger

### ISSUE THREAD

**Issue by jb08** [scalatra/scalatra#646]
As a developer, I need the ability to deprecate endpoints in swagger. For instance, see the deprecated `/pet/findByTags` endpoint in [petstore swagger](http://petstore.swagger.io/v2/swagger.json).

not sure why not working: [deprecate method](https://github.com/scalatra/scalatra/blob/2.5.x/swagger/src/main/scala/org/scalatra/swagger/SwaggerSupport.scala#L251)

Scalatra endpoint:

` apiOperation[Object]("filter")
      deprecate
      summary ("filter something")
      parameter pathParam[String]("field").description("The field to filter on").required
      responseMessages(
      ResponseMessage(code = 401, message = "returns 401 (Unauthorized) if no api-key", responseModel = None)
    )
`

yet `deprecated` does not show up as property in swagger, 
`
  "/filter/{field}": {
      "get": {
        "operationId": "filter",
        "summary": "filter something",
        "parameters": [
          {
            "name": "field",
            "description": "The field to filter on",
            "required": true,
            "in": "path",
            "type": "string"
           }]
`

**Comment by jb08** [comment]
I will work on this and do a first PR if someone can point me in right direction.

**Comment by takezoe** [comment]
@jb08 What Swagger version are you specifying? `deprecated` annotation has been deprecated in Swagger 2.0, so Scalatra's Swagger 2.0 support does not renderer it.

**Comment by jb08** [comment]
I'm using swagger 2.0. Where did you see that the `deprecated` field was deprecated? From the [changelog](https://github.com/OAI/OpenAPI-Specification/wiki/swagger-1.2-to-2.0-migration-guide): 
> The deprecated field type has changed to boolean.

Let me know if I should do a PR to re-enable `deprecate` function.

**Comment by takezoe** [comment]
@jb08 Oops. Sorry, I had been confused it as an another property. Yes, `deprecated ` can be rendered as boolean property in Swagger 2.0. I will fix this in 2.5.1 or 2.6.0.

**Comment by jb08** [comment]
this issue can be closed as complete imo
