### ISSUE TITLE
Getting Started - Suggest SDKMAN

### ISSUE THREAD

**Issue by aadrian** [scalatra/scalatra#660]
The installation step in "Getting Started" tutorial is way too cumbersome and confusing

Please update it to something simpler, e.g. like when using SDKMAN:

```
% sdk install java
% sdk install sbt
% sdk install scala
```

Also ```giter8``` is not required anymore since it's build in SBT since 0.13.13 http://www.scala-sbt.org/0.13/docs/sbt-new-and-Templates.html

So in http://scalatra.org/getting-started/first-project.html it should also be:
```sbt new scalatra/scalatra-sbt.g8```

**Comment by magnolia-k** [comment]
Since it has been rewritten to use `sbt new`, I think it has become simple enough, but what about?

**Comment by magnolia-k** [comment]
Since the sbt installation manual now includes an example of SDKMAN, I think this issue can be closed.

https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html
