### ISSUE TITLE
org.scalatra.swagger.StringResponseMessage is preserved in scalatra-swagger_2.11-2.5.0.jar

### ISSUE THREAD

**Issue by yarulan** [scalatra/scalatra#665]
I updated scalatra in my project from 2.4.1 to 2.5.0 and noticed that class `org.scalatra.swagger.StringResponseMessage` is gone from the source code but it is still present in `scalatra-swagger_2.11-2.5.0.jar`. How is that possible?

**Comment by takezoe** [comment]
@yarulan Use `ResponseMessage` with `responseModel = None` instead.

**Comment by yarulan** [comment]
@takezoe Thanks, but that was not my question.

**Comment by takezoe** [comment]
@yarulan Oops, I misread. I'm not sure about 2.5.0 release because I didn't publish it by my hand, but I think maybe it was operation miss (e.g. it was packaged without cleaning existing resources). 

Could you check the latest 2.5.1 which was released a few days ago?

**Comment by yarulan** [comment]
@takezoe It's not present in 2.5.1 anymore. Thank you.
