### ISSUE TITLE
Swagger 2.0 BodyParam Container Types Broken

### ISSUE THREAD

**Issue by natevecc** [scalatra/scalatra#677]
Scalatra Version: 2.5.1

I think the logic on this [line](https://github.com/scalatra/scalatra/blob/016127685de5b239679cbfc50d091529d82db595/swagger/src/main/scala/org/scalatra/swagger/SwaggerBase.scala#L152) is wrong.

Right now if I do 
```scala
bodyParam[List[String]]("body")
```
The swagger generated doesn't recognize the list as a container but instead treats it as a type definition:
```json
{
  "name": "body",
  "required": true,
  "in": "body",
  "schema": {
    "$ref": "#/definitions/List"
  }
}
```
But for a query param it works fine:
```scala
 queryParam[List[Long]]
```
Swagger output:
```json
{
  "name": "layerIds",
  "required": true,
  "in": "query",
  "type": "array",
  "items": {
    "type": "integer",
    "format": "int64"
  }
}
```

I don't think there should be a difference between body and the other param types unless there's an edge case I'm not thinking of.

**Comment by takezoe** [comment]
Fixed in #693. It will be released in Scalatra 2.6.0.
