### ISSUE TITLE
Swagger 2.0 Map type not handled correctly

### ISSUE THREAD

**Issue by natevecc** [scalatra/scalatra#678]
Scalatra Version: 2.5.1

Given:
```scala
case class ChangeResponse(success: Boolean, message: Option[String] = None)
apiOperation[Map[String, ChangeResponse]]("shareDataSet")
```
Scaltra Swagger generats:
```json
{
  "responses": {
    "200": {
      "description": "OK",
      "schema": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  }
}
```

In the version of the code I have there's a `GenMap` case class that looked like it was used to handle this but it's commented out and not used. What was the reason for this regression?

**Comment by takezoe** [comment]
@natevecc `Map` should be handled as `object` type in Swagger, but I think it's impossible to extract properties from that definition. What JSON should be generated from your definition?

**Comment by natevecc** [comment]
It looks like the recommended approach is to use `additonalProperties`. [Here](https://stackoverflow.com/a/41242185) is an explanation of it and how it works. It appears to only work with swagger 2.0 tho.
