### ISSUE TITLE
[Swagger 2] notes are disregarded

### ISSUE THREAD

**Issue by salceson** [scalatra/scalatra#680]
The `notes` field is no longer present in Swagger 2 Operation specification, though the `description` field has been introduced, more or less they serve the same purpose.

From https://github.com/OAI/OpenAPI-Specification/wiki/Swagger-1.2-to-2.0-Migration-Guide:

> Operation's notes field was renamed to description

I propose either to change rendering of Swagger 2 operations to include the `notes` contents of Scalatra's `SwaggerOperation`s or add `description` to the `SwaggerOperation` itself.

**Comment by takezoe** [comment]
Added description as a part of #681. Scalatra 2.6.0 supports both description and notes, and notes will be dropped in 2.7.0 or 3.0.0 with dropping Swagger 1.x support.
