### ISSUE TITLE
Scalatra-Json4s not serializing non-case classes with FieldSerializer

### ISSUE THREAD

**Issue by gursahibexp** [scalatra/scalatra#683]
### jdk version - 8

I am trying to return a non-case class object as a JSON to a POST endpoint. I am using the FieldSerializer assuming it would parse the non-case to a JSON and return the response.

Code snippet : ` protected implicit lazy val jsonFormats: Formats = DefaultFormats + FieldSerializer[ResponseStatus]() +FieldSerializer[SubmitClaimResponse]()
 `
But it doesn't work that way 

Why am not using case classes because these classes are imported as a contract in my scalatra API codebase. jsonschemtopojo converts the json schema to respective non-case classes 

Alternatively, is there any way I can convert my jsonschema to case classes using some library. I couldnt find any

**Comment by takezoe** [comment]
@gursahibexp I tested `FieldSerializer` with POJO and it worked fine.

POJO:
```java
public class Pojo {

    private int status;
    private String message;

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
```

Test case:
```scala
val pojo = new Pojo()
pojo.setStatus(200)
pojo.setMessage("OK")

"POJO fields are serialized" in {
  implicit val formats = DefaultFormats + FieldSerializer[Pojo]()
  val ser = swrite(pojo)
  val pojo2 = read[Pojo](ser)
  pojo2.getStatus must_== pojo.getStatus
  pojo2.getMessage must_== pojo.getMessage
}
```
Could you publish tiny project to reproduce your situation?

**Comment by gursahibexp** [comment]
@takezoe I don't have access to that project anymore and am sorry that I can't post any snippet of the project. But I remember that the object wasn't getting deserialized. The GET response was throwing back the reference of that object. I remember using GSON explicitly for the deserialization process and send back `JSON String` in the response and not the object itself. 

Hopefully, this give some more clarity

**Comment by magnolia-k** [comment]
Then close because no one is reporting a similar problem.
If a new problem arises, create another issue.
