### ISSUE TITLE
Clarify Scalatra's support policy

### ISSUE THREAD

**Issue by magnolia-k** [scalatra/scalatra#690]
Currently, the website has a link from version 2.3 to 2.5. Version 2.6 will be released soon, but maybe we need to clarify our support policy?

In particular, considering the maintenance of documentation and sample code, it is better to clarify support, such as upgrading to two versions.

**Comment by takezoe** [comment]
In my opinion, we should add new features to the next development version (currently it's 2.6.0), and keep maintain for the latest stable series (currently it's 2.5.x).

However I expect that 3.0.0 will break compatibility in a lot of points. So we might have to keep maintain for the latest stable version of both 2.x series and 3.x series after 3.0.0 release.

Also, maintaining documents is same. We don't need to remove old documents actively, but we should maintain them according to the above policy.
