### ISSUE TITLE
Support for additionalProperties swagger tag is missing

### ISSUE THREAD

**Issue by adrake-uptake** [scalatra/scalatra#700]
There doesn't seem to be a way to set the 'additionalProperties' property of a Schema Object to specify that an object in the swagger document is a map. Looking at the org.scalatra.swagger.Model generated during the SwaggerOperation I don't see any way to get a root level additionalProperties definition into the resulting swagger doc.

**Comment by takezoe** [comment]
Duplicate with #678.
