### ISSUE TITLE
MultiMap broken

### ISSUE THREAD

**Issue by xuwei-k** [scalatra/scalatra#724]
```
Welcome to Scala 2.12.3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_151).
Type in expressions for evaluation. Or try :help.

scala> import org.scalatra.util.MultiMap
import org.scalatra.util.MultiMap

scala> var m = MultiMap.empty
m: org.scalatra.util.MultiMap = Map()

scala> m += ("a" -> 1)

scala> m
res0: org.scalatra.util.MultiMap = Map(a -> 1)

scala> m.get("a").head
java.lang.ClassCastException: java.lang.Integer cannot be cast to scala.collection.Seq
  ... 37 elided
```

https://github.com/scalatra/scalatra/blob/0fb17fa0d6495976b78e147c3129765b6045accb/core/src/main/scala/org/scalatra/util/MultiMap.scala#L27

**Comment by takezoe** [comment]
I'm proceeding refactoring of the whole codebase for Scalatra 2.6 in #729 and succeeded to drop `MultiMap` in https://github.com/scalatra/scalatra/pull/729/commits/5d9c326a9b0b5291120d312971f900b272192962.
