### ISSUE TITLE
Getting started with Scalatra and Scalate

### ISSUE THREAD

**Issue by davidsavoie1** [scalatra/scalatra#728]
I'm an absolute beginner with Scala, Scalatra and Scalate and I don't have a Java background. However, after reading about these languages and tools, I'm eager to learn them to make more robust and clean applications. I need help just getting started with a simple Scalate project so I can practice a bit...

I succesfully completed the getting started guide for [Scalatra](http://scalatra.org/getting-started/first-project.html) and I want to try out Scalate with Jade or some other templating tool. However, when I try to follow [this guide](http://scalatra.org/guides/2.5/views/scalate.html), I get stuck at the first line of code:
```
class YourServlet extends ScalatraServlet with ScalateSupport
```
I get this obvious error: `not found: type ScalateSupport`. I understand that I need to import it in my project somehow. The documentation says:
> Using the ScalateSupport helper trait which comes built into the default Scalatra g8 template.

Nothing in the guide indicates how to make it work. Could someone please refer me to some information about this kind of absolute basics? And feel free to tell me if I should have posted this question elsewhere!

Thank you for helping me get into the Scalatra world!

**Comment by takezoe** [comment]
@davidsavoie1 

> Using the ScalateSupport helper trait which comes built into the default Scalatra g8 template.

Sorry, g8 template has been updated to use Twirl template. We have to update documentation.

To enable Scalate in your project, add following dependency to your `build.sbt`:

```scala
"org.scalatra" %% "scalatra-scalate" % ScalatraVersion
```

**Comment by takezoe** [comment]
This example project might help you to know usage of Scalate in the Scalatra project:
https://github.com/scalatra/scalatra-website-examples/tree/master/2.5/persistence/scalatra-squeryl

**Comment by davidsavoie1** [comment]
Thanks for your reply, I managed to make it work alright. However, I had to copy a line from the example you pointed me to:
```
import scalate.ScalateSupport
```
This kind of information would be critically important (in my opinion) to include in the documentation to help newcomers get started. Thanks again, can't wait to dive deeper.

**Comment by takezoe** [comment]
Exactly. I filed documentation update as https://github.com/scalatra/scalatra-website/issues/160.

**Comment by davidsavoie1** [comment]
I've just found out about [Scaladex](https://index.scala-lang.org/), which could compare to NPM I guess for Node users. I searched for Scalate there and found [this page](https://index.scala-lang.org/scalate/scalate/sbt-scalate-plugin/1.7.1?target=_2.10), which indicates the following dependency syntax:
```
"org.scalatra.scalate" %% "sbt-scalate-plugin" % "1.7.1"
```
Would that yield the same result as the proposed `"org.scalatra" %% "scalatra-scalate" % ScalatraVersion` or is it completely different?

Thanks again!

**Comment by takezoe** [comment]
```scala
"org.scalatra.scalate" %% "sbt-scalate-plugin" % "1.7.1"
```
This is a sbt plugin which had been provided by the old version of Scalate. It enables Scalate in your project but it's too old to use now.
```scala
"org.scalatra" %% "scalatra-scalate" % ScalatraVersion
```
This is a sub module of Scalatra to integrate Scalate with Scalatra application. I strongly recommend to use this.

**Comment by davidsavoie1** [comment]
Any way I could have known that? How can I know if a project on Scaladex is reliable, up-to-date or obsolete? I'm asking, because I'm looking for a way to be self-reliant as much as possible.

Thanks for all your help, very much appreciated!

**Comment by takezoe** [comment]
About Scalatra, the most reliable information is the official documentation and examples (Sorry for lack of update of documentation):

- http://scalatra.org/guides/
- https://github.com/scalatra/scalatra-website-examples

In Scaladex, you can see and select a library version at the right side of the top. For scalate, you can find 1.8.0 as the latest version there.
