### ISSUE TITLE
Swagger bodyParam[String] is interpreted incorrectly

### ISSUE THREAD

**Issue by dimparf** [scalatra/scalatra#742]
Scalatra 2.5.1. Swagger 2
If I define a bodyParam[String] swagger produce this message (in UI):
`Could not resolve reference because of: Could not resolve pointer: /definitions/string does not exist in document`
And my swagger.json fragment:
```
"/project/predict/{id}/?": {
  "post": {
   "operationId": "Get category, sentiment and named entities as prediction JSON",
   "summary": "Get prediction",
   "deprecated": false,
   "parameters": [
    {
    "name": "body",
    "description": "Text for natural language processing",
    "required": true,
    "in": "body",
    "schema": {
      "$ref": "#/definitions/string" //WTF ?
    }
 },
 {
  "name": "id",
  "description": "Project id",
  "required": true,
  "in": "path",
  "type": "string" //this is correctly
  }
]
```

**Comment by takezoe** [comment]
@dimparf Could you show the annotated source code?

**Comment by dimparf** [comment]
```
val predictWithBody =
    (apiOperation[Prediction]("Get category, sentiment and named entities as prediction JSON")
      summary "Get prediction"
      notes "You must have a API key and authorization token"
      parameter pathParam[String]("id").description("Project id")
      parameter bodyParam.description("Text for natural language processing"))
```
and my controller code:
```
post("/predict/:id/?", operation(predictWithBody)) {
    val id = params("id")
    val text = request.body
    new AsyncResult() {
      val is = projectService.predict(id, text) //return category, sentiment, named entities
    }
  }
```

**Comment by takezoe** [comment]
@dimparf Thanks for information! I fixed in f6c6f5b84230b3d9cca4010878a6d402702512bf.
It will be released in Scalatra 2.6.0, but it will take some more time. Instead, we can release 2.5.4 before 2.6.0. Let me know if you need it.

**Comment by dimparf** [comment]
@takezoe Thanks)

**Comment by takezoe** [comment]
@dimparf OK, I will release 2.5.4 as soon as possible.

**Comment by takezoe** [comment]
@dimparf Published 2.5.4. It takes a while to be available on the Maven central repository.

**Comment by dimparf** [comment]
Thanks @takezoe

**Comment by takezoe** [comment]
By the way, according to the Swagger 2.0 specification, it seems that `body` parameter doesn't allow other than `schema`. What is the correct result...?
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object

**Comment by dimparf** [comment]
@takezoe hmm, yes schema is correct for body, but $ref to string leads to an error in Swagger UI.
