### ISSUE TITLE
ScalateSupport can't be used with ScalatraFilter 

### ISSUE THREAD

**Issue by takezoe** [scalatra/scalatra#769]
`ScalateSupport` extends `ServletBase`, so it seems that it can't be used if controllers are implemented as `ScalatraFilter`.

Isn't it possible to make it useable with `ScalatraFilter`, not only with `ScalatraServlet`?

**Comment by magnolia-k** [comment]
I think that it works also with Filter.
Do you have any code examples that do not work?

**Comment by takezoe** [comment]
Scalate will be deprecated in the future version of Scalatra, anyway.
