### ISSUE TITLE
Why is the auth component called "Scentry"?

### ISSUE THREAD

**Issue by enragedginger** [scalatra/scalatra#780]

**Comment by takezoe** [comment]
I don't know... It was already named when I joined Scalatra team. Does anyone know?

CC/@casualjim @rossabaker @dozed @seratch

**Comment by seratch** [comment]
I have no idea.

**Comment by aadrian** [comment]
> Why is the auth component called "Scentry"?

Maybe "SCalatra Entry" ? :)

**Comment by casualjim** [comment]
when I originally wrote this module, it was modelled after sentry from ruby for sinatra. So i made it scala sentry.

**Comment by enragedginger** [comment]
@casualjim Ah, that makes scense. Thank you!
