### ISSUE TITLE
jetty:start is not a valid key

### ISSUE THREAD

**Issue by fivefreshfish** [scalatra/scalatra#781]
[root@scala editable]# sbt new scalatra/scalatra.g8
[info] Set current project to editable (in build file:/root/scala/editable/)
organization [com.example]: com.salamander
name [My Scalatra Web App]: General Table Editor
version [0.1.0-SNAPSHOT]:
servlet_name [MyScalatraServlet]: editable
package [com.example.app]: com.salamander.scala.web
scala_version [2.12.4]:
sbt_version [1.0.4]:
scalatra_version [2.6.2]:

Template applied in ./general-table-editor

[root@scala editable]# ls
general-table-editor  target
[root@scala editable]# sbt
[warn] No sbt.version set in project/build.properties, base directory: /root/sca                                                                                                                                                             la/editable
[info] Set current project to editable (in build file:/root/scala/editable/)
> jetty:start
[error] Not a valid key: start (similar: state, startYear, target)
[error] jetty:start
[error]            ^

**Comment by takezoe** [comment]
You have to change current directory to `general-table-editor` before run `sbt`.

```
$ cd general-table-editor/
$ sbt
...
> jetty:start
```

**Comment by fivefreshfish** [comment]
Thank you for your reply. The instructions on the first project page were confusing, it says 'cd /your/project/directory', I thought I was already in my project directory and that general-table-editor was the servlet directory.

**Comment by magnolia-k** [comment]
The document states 'Enter your application's top-level directory', but was it hard to understand?

**Comment by magnolia-k** [comment]
The issue will then close, as the issue does not seem to be continuing.
