### ISSUE TITLE
CORS header Access-Control-Allow-Origin missing causing browsers to block cross domain requests

### ISSUE THREAD

**Issue by toefel18** [scalatra/scalatra#797]
Scalatra does not send the `Access-Control-Allow-Origin` response header with CorsSupport mixed in. Without this header the browsers block the requests. This problem exists since Scalatra version 2.5.1. 

Workaround: downgrade to Scala 2.5.0. This is the only version for scala 2.12 that works for us. 

The [CORS documentation](http://scalatra.org/guides/2.6/web-services/cors.html)

Example code:
```
import org.scalatra.CorsSupport

class YourServlet extends ScalatraBase with CorsSupport {
  options("/*"){
    response.setHeader("Access-Control-Allow-Origin", "*");
  }
}
```

I do not see this header when I do a cross-domain request with the browser (the other headers I do see!). When I simulate a raw HTTP request with telnet, the header is missing as well.

**Comment by magnolia-k** [comment]
The change of CorsSupport in scalatra 2.5.1 is the following commitment, will it be helpful?

https://github.com/scalatra/scalatra/commit/dde3c04388c3a3abd82a193ed21c656509ee91a1#diff-92c75d9fdef89c841ebc2bab2ffdc778

**Comment by takezoe** [comment]
Also, my explanation in https://github.com/scalatra/scalatra/issues/695 might help you.

**Comment by toefel18** [comment]
I will retest it with the comments of @takezoe

**Comment by toefel18** [comment]
Everything seems to work after I set the init param
```
context.initParameters("org.scalatra.cors.allowCredentials") = "false"
```

I think should be emphasized in the documentation. I did look for solutions and read the docs, but that init parameter does not feel logical. I can close this issue but

**Comment by takezoe** [comment]
@toefel18 Yes! Please request on the website repository:
https://github.com/scalatra/scalatra-website
