### ISSUE TITLE
200 response always included in swagger2 documentation

### ISSUE THREAD

**Issue by cianom** [scalatra/scalatra#798]
Swagger always includes a 200 response and doesn't provide an option to override. 

There are cases where we only want to return 201 or 204 and 200 still gets included in the responses, which is misleading.

Noticed in `scalatra-swagger_2.11-2.6.2`
See class `org.scalatra.swagger.SwaggerBaseBase#renderSwagger2`
Code:
```
("responses" ->
  ("200" ->
    (if (operation.responseClass.name == "void") {
      List(JField("description", "No response"))
    } else {
      List(JField("description", "OK"), JField("schema", generateDataType(operation.responseClass)))
    })) ~
    operation.responseMessages.map { response =>
      (response.code.toString ->
        ("description", response.message) ~~
        response.responseModel.map { model =>
          List(JField("schema", JObject(JField("$ref", s"#/definitions/${model}"))))
        }.getOrElse(Nil))
    }.toMap) ~!
    ("security" -> (operation.authorizations.flatMap { requirement =>
      swagger.authorizations.find(_.`keyname` == requirement).map {
        case a: OAuth => (requirement -> a.scopes)
        case b: ApiKey => (requirement -> List.empty)
        case _ => (requirement -> List.empty)
      }
    }))))
```

**Comment by nathansolomonspears** [comment]
Can I suggest removing the 200 entirely? If I create a ResponseMessage with code 200, it causes duplicate 200 statuses to be created, which breaks the new Swagger UI, on top of being the wrong output. Perhaps a boolean for "create default 200 status", false by default?

**Comment by lawrencecraft** [comment]
Is anyone looking at this? 

We've got API methods that return 201 and others. Unfortunately this still appears to be the case in the current codebase.

I can look at this and submit a PR if not.
