### ISSUE TITLE
XSS in 404 route listing

### ISSUE THREAD

**Issue by CarlEkerot** [scalatra/scalatra#799]
There's an XSS vulnerability in the developer 404 route listing:
```
$ curl "http://localhost:8080/anypath%3Cimg%20src%3da%20onerror%3dalert(1)%3E"
Requesting "GET \/anypath<img src=a onerror=alert(1)>" on servlet "" but only have: <ul><li>GET /</li></ul>
```

The javascript alert is prevented by most major browsers except Firefox. I've verified that the vulnerability in the sample app from http://scalatra.org/getting-started/first-project.html running on 2.6.2

**Comment by CarlEkerot** [comment]
Just noticed that #578 was an attempt to solve this issue. From the looks of it, ``escapeEcmaScript`` is not sufficient to prevent XSS. HTML escaping is probably needed.

**Comment by takezoe** [comment]
#610 seems to be a solution.
