### ISSUE TITLE
Swagger error on swagger.json when body has a multivalued dataType

### ISSUE THREAD

**Issue by GastonTS** [scalatra/scalatra#823]
Hi I'm having trouble  with Collection body parameters in Swagger support.  The thing is the swagger.json generated when I use a list or multivalued  datatype is

```
parameters: [
    {
        name: "parameterName",
        required: true,
        in: "body",
        type: "array",
        items: {
            $ref: "#/definitions/MyCaseClass"
        }
    }
],
```

When this happens I can't use the Try it out! since there's no example or box to put my body. Looking at swagger documentation i see that even when there are or multivalued types there must be a schema object that encapsulet the type and items. This can be seen in [this swagger example](http://petstore.swagger.io/#/user/createUsersWithArrayInput). The swagger.json of that example is,

```
parameters: [
    {
        in: "body",
        name: "body",
        description: "List of user object",
        required: true,
        schema: {
        type: "array",
        items: {
            $ref: "#/definitions/User"
        }
    }
}
```

As you can see [here](http://petstore.swagger.io/v2/swagger.json).

Looking on [SwaggerBase](https://github.com/scalatra/scalatra/blob/91178a19c513a7dbf61d3d0d737f8ab749a482ca/swagger/src/main/scala/org/scalatra/swagger/SwaggerBase.scala) in the render method there is an if.

https://github.com/scalatra/scalatra/blob/91178a19c513a7dbf61d3d0d737f8ab749a482ca/swagger/src/main/scala/org/scalatra/swagger/SwaggerBase.scala#L119-L124

Which eventually decides if it should append the schema like a father key to the data types. Is there a reason for that? Is there a way to fix this or get a List/Map/etc body with the example in swagger to Try it out?

Could be related with #310

Thanks in advance!

**Comment by GastonTS** [comment]
Could be related with #310

**Comment by takezoe** [comment]
I tested following Swagger Scalatra definition:

```scala
val testOperation = (apiOperation[MyResult]("test")
  parameters (bodyParam[Array[MyCaseClass]])
)
```

This definition generated a parameters as below in swagger.json:

```json
"parameters": [{
  "name": "body",
  "required": true,
  "in": "body",
  "schema": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/MyCaseClass"
    }
  }
}],
```

It looks to be working fine from this result. Could you show your Scalatra Swagger definition which generates a parameter without schema property?

**Comment by GastonTS** [comment]
Hi, my swagger definition looks like this

```
  val putMetrics: OperationBuilder =
    (apiOperation[BasicResponse]("putMetrics")
      summary "Push a list of metrics"
      description "Push each metric recieved to the list."
      tags "Metrics"
      parameter bodyParam[List[ExternalMetric]]("List of metrics"))
```

I've tested replacing List with Array but still doesn't work.Anyway i've tested your swagger config and didn't get the same output, with the testOperation I'm getting,

```
parameters: [
    {
        name: "body",
        required: true,
        in: "body",
        type: "array",
        items: {
            $ref: "#/definitions/ExternalMetric"
        }
    }
],
```

May be it's a configuration or version issue. I'm using Scalatra "scalatra", "scalatra-json", "scalatra-swagger" all with 2.6.1 version. The only difference with the [swagger example](https://github.com/scalatra/scalatra-website-examples/tree/master/2.6/swagger-example) it's that I'im using Jackson instead of Native json support traits.

**Comment by GastonTS** [comment]
Testing with the swagger example if you change 2.6.+ to 2.6.1 you can replicate the bad behavior. Do you know in which release this was fixed so i can set a fixed version to my scalatra project?
