### ISSUE TITLE
Mimes trait detects the wrong MIME type

### ISSUE THREAD

**Issue by helfper** [scalatra/scalatra#830]
`Mimes` trait seems to always return `application/octet-stream` as MIME type.

Currently:
```scala
scala> MimeTypes.mimeType("test.html")
res0: String = application/octet-stream
```

Expected:
```scala
scala> MimeTypes.mimeType("test.html")
res0: String = text/html
```

Problem:

`mimeUtil` is a definition instead of a variable. Every time `mimeUtil` is used it creates a brand new instance of `MimeUtil2` and looses the `MimeDetector` registrations.

https://github.com/scalatra/scalatra/blob/0474fb35ee19a5b30f9bab8947ea92a84948a9e8/core/src/main/scala/org/scalatra/util/Mimes.scala#L38-L40

Solution:

Make `mimeUtil` a `val` instead of `def` in the trait `org.scalatra.util.Mimes`

---

Unfortunately, that's not the end of the story. Even with that fix, `Mimes` returns the wrong MIME type for CSS files.

```scala
scala> MimeTypes.mimeType("test.css")
res1: String = application/x-pointplus
```

Now the problem is coming from `eu.medsea.mimeutil` library, which has both `application/x-pointplus` and `text/css` MIME types associated with the extension `.css`, and will pick one of them mostly randomly (both MIME types end up inside a `HashSet` at some point, so it's not guaranteed which one will come out first). This, from my point of view, makes this library unfit for purpose.

Other projects have already moved away from that library, being Apache Marmotta one of them that chose Apache Tika as an alternative (https://git-wip-us.apache.org/repos/asf?p=marmotta.git;a=commitdiff;h=f89f61f2128fcb70db885b31b42077782ad411a6), and it seems it's a quite reliable library.

```scala
scala> tika = new org.apache.tika.Tika
tika: org.apache.tika.Tika = Apache Tika 1.18

scala> tika.detect("test.html")
res2: String = text/html

scala> tika.detect("test.css")
res3: String = text/css
```

**Comment by magnolia-k** [comment]
Since Mines has neither test nor document, should it be better to deprecated and recommend using Files.probeContentType?

**Comment by helfper** [comment]
I'm fine with deprecating and eventually removing it, but it's currently being used in `ScalatraBase` in a way that is not covered by `Files.probeContentType` AFAIK:

https://github.com/scalatra/scalatra/blob/c7f214dc69cd381bf4be6eb36dac9873709885e0/core/src/main/scala/org/scalatra/ScalatraBase.scala#L288-L290

In that case, the Content-Type auto-inference feature would have to be removed (which I believe never worked properly anyway).

**Comment by magnolia-k** [comment]
It may be possible to use 'java.net.URLConnection.guessContentTypeFromStream'

**Comment by magnolia-k** [comment]
I will organize it a little more and write a PR

**Comment by magnolia-k** [comment]
Added MIME type customization example to the test

https://github.com/scalatra/scalatra/pull/836/commits/03b0fbdeee17da08376dfc53bfe08c30f919f6f6

**Comment by magnolia-k** [comment]
https://github.com/scalatra/scalatra/pull/839

**Comment by takezoe** [comment]
Can I close this issue?
