### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by xuwei-k** [scalatra/scalatra#831]
- [x] akka https://github.com/akka/akka/issues/25105
- [x] scala-parser-combinators https://github.com/scala/scala-parser-combinators/issues/151
- [x] scalate https://github.com/scalate/scalate/issues/133
- [x] scalatest https://github.com/scalatest/scalatest/issues/1367
- [x] specs2 https://github.com/etorreborre/specs2/issues/666
- [x] metrics-scala (depends on akka)
- [x] twirl https://github.com/playframework/twirl/pull/180

**Comment by SethTisue** [comment]
Akka issue is https://github.com/akka/akka/issues/25105

**Comment by SethTisue** [comment]
Akka and Twirl have published for M5

so has metrics-scala: https://repo1.maven.org/maven2/nl/grons/metrics4-scala_2.13.0-M5/4.0.4/

so perhaps this could move forward?

**Comment by xuwei-k** [comment]
https://github.com/scalatra/scalatra/pull/940

**Comment by magnolia-k** [comment]
Merged!
