### ISSUE TITLE
scalatra.org not working

### ISSUE THREAD

**Issue by sterowney** [scalatra/scalatra#848]
When navigating to http://www.scalatra.org/ I get the follow error.

It means I can't view the documentation 👎 

![image](https://user-images.githubusercontent.com/1401719/43254454-b368ca86-90c7-11e8-90eb-41d5584dc22d.png)

**Comment by takezoe** [comment]
The website has already been back. See also #843.

**Comment by sterowney** [comment]
it works now for http://scalatra.org but not for http://www.scalatra.org

https://www.webpagetest.org/result/180726_28_340cfd181bb2bba982b9a4d7815f5401/

**Comment by sterowney** [comment]
Fair enough, then its resolved.
