### ISSUE TITLE
CORS Issues: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by dadepo** [scalatra/scalatra#855]
Scalatra version: 2.5.4.
Scala version: 2.11

When a cross-origin request is made, it fails with the following error: 
```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
```
The Scalatra application is registered in web.xml as a servlet. It looks like this:

```
    <servlet>
        <servlet-name>apiResource</servlet-name>
        <servlet-class>app.api.RootApiResource</servlet-class>
        <init-param>
            <param-name>org.scalatra.cors.allowCredentials</param-name>
            <param-value>false</param-value>
        </init-param>
        <init-param>
            <param-name>org.scalatra.cors.allowedOrigins</param-name>
            <param-value>*</param-value>
        </init-param>
        <load-on-startup>0</load-on-startup>
    </servlet>
```

The `RootApiResource` looks like this:

```
class RootApiResource
  extends ScalatraServlet
    with Logging
    with SomeOtherTraits
    with CorsSupport {

  override val baseDocUrl: String = "/api"

  options("/*") {
    response.setHeader("Access-Control-Allow-Headers", request.getHeader("Access-Control-Request-Headers"))
    response.setHeader("Access-Control-Allow-Origin", request.getHeader("Origin"))
  }

}
```

Would you be kind enough to help out with this? What could be wrong in the configuration above, assuming this is not a bug.

PS: This works with Scalatra version 2.4.1. It is with the upgrade to 2.5.4 that the cors issue starts popping up.

**Comment by dadepo** [comment]
When I check the headers in my response I see:
`Access-Control-Allow-Credentials: true` (which means the settings above is not having any effect)

and I do not see the other `Access-Control-*` headers. This is definitely the problem. But why the configuration above is not working? is what I do not know yet.

**Comment by takezoe** [comment]
@dadepo Try to set parameters as `context-param`, not servlet's `init-param`:

```xml
<web-app>
  <context-param>
    <param-name>org.scalatra.cors.allowCredentials</param-name>
    <param-value>false</param-value>
  </context-param>
  <context-param>
    <param-name>org.scalatra.cors.allowedOrigins</param-name>
    <param-value>*</param-value>
  </context-param>
  ...
</web-app>
```
The reason of why your application does't work after upgrading to 2.5.4 is the default behavior of CORS support has been chaned since 2.5.x.

I guess your configuration hadn't worked actually in Scalatra 2.4.x, but CORS support had worked in the default behavior. In 2.5.x, CORS doesn't work with the default behavior, so you have to configure correctly.

**Comment by dadepo** [comment]
Thanks, @takezoe Indeed I should have been configuring the `context-param` instead of `init-param`
I updated the documentation to include the corresponding xml configuration here https://github.com/scalatra/scalatra-website/pull/185
