### ISSUE TITLE
Dead link in Scaladoc

### ISSUE THREAD

**Issue by bobbyi** [scalatra/scalatra#893]
The Scaladoc for org.scalatra.DynamicScope (https://static.javadoc.io/org.scalatra/scalatra-unidoc_2.12/2.6.0/org/scalatra/DynamicScope.html) refers to the blog post http://www.riffraff.info/2009/4/11/step-a-scala-web-picoframework for more explanation. However, that blogpost no longer exists (the registration for the domain has expired). 

The post is still accessible with the Wayback Machine, so perhaps you could change to using that URL or get permission from the author to rehost the post on scalatra.org

**Comment by magnolia-k** [comment]
thanks!

This link will be deleted
