### ISSUE TITLE
Unnecessary escape character in Scalatra guides

### ISSUE THREAD

**Issue by counter2015** [scalatra/scalatra#895]
I'm new on Scalatra, when I learn from Scalatra Website guides, I meet a confused problem in the following link : http://scalatra.org//guides/2.6/http/routes.html

In `Regular expressions` section, there is a example 
```scala
get("""^\/f(.*)/b(.*)""".r) {
  // Matches "GET /foo/bar"
  multiParams("captures") // == Seq("oo", "ar")
}
```
The regular expression `^\/f(.*)/b(.*)` makes me confused.
If the symbol `/` has specific meaning, why not write like `^\/f(.*)\/b(.*)`,
in fact, I have test the code, all of the following expression worked
- `^\/f(.*)/b(.*)`
- `^/f(.*)/b(.*)`
I don't know whether is a typo or not, or I misunderstand?

----
UPD. I just realized there is a repository named scalatra-website, 
If I cause trouble, I apologize beforehand for my recklessness.

**Comment by magnolia-k** [comment]
As you point out, that backslash is unnecessary.
PR is welcome :)

**Comment by counter2015** [comment]
> As you point out, that backslash is unnecessary.
> PR is welcome :)

 
Thanks for your reply. I have made a [PR](https://github.com/scalatra/scalatra-website/pull/188) here.

**Comment by magnolia-k** [comment]
merged!
