### ISSUE TITLE
Docs: "Project news" is outdated

### ISSUE THREAD

**Issue by exoego** [scalatra/scalatra#938]
http://scalatra.org/

"Project news" section is not updated.
[There are many releases](https://github.com/scalatra/scalatra/releases) out there.
I think updating new is benefical for casual users to find latest release.

**Comment by magnolia-k** [comment]
That's right.
I will update in the near future.

**Comment by magnolia-k** [comment]
https://github.com/scalatra/scalatra-website/pull/189

**Comment by takezoe** [comment]
Merged and deployed: http://scalatra.org/2019/02/15/2019-02-15-scalatra-2-6-5-released.html
