### ISSUE TITLE
Lossy decoding in UriDecoder

### ISSUE THREAD

**Issue by ingemaradahl** [scalatra/scalatra#964]
Our application has something similar to 
```scala
get("/url/:url/hits") {
  calculateHits(params("url"))
}
```
As you can imagine, requests are made like `GET /url/https%3A%2F%2Fexample%2Ftest%3Ffoo%3Dbar/hits` (for `https://example/test?foo=bar`) and this has been working fine for a lot of years. However we've noticed that for urls which unencoded contains `%3F` things break. For instance consider getting the "hits" for `https://example/?id=%3F`: `GET /url/https%3A%2F%2Fexample%2F%3Fid%3D%253F/hits`. When this is handled by Scalatra, `params("url")` returns `https://example/?id=?`.

https://github.com/scalatra/scalatra/issues/52 seems to be what introduced this behavior as certain characters are handled separately (among them `%3F -> ?`). You can see this for yourself by running the following in the Scala REPL:
```scala
import org.scalatra.UriDecoder
val uri = "/url/https%3A%2F%2Fexample%2F%3Fid%3D%253F/hits"
val u0 = UriDecoder.firstStep(uri)
UriDecoder.secondStep(u0)
```
which yields `/url/https://example/?id=?/hits`. In the route above `param("url")` won't actually return what the user actually requested and things break. This is the issue we're having.

I experimented a bit by trying out the following patch:
```diff
diff --git a/core/src/main/scala/org/scalatra/PathPatternParsers.scala b/core/src/main/scala/org/scalatra/PathPatternParsers.scala
index 2b58bdf0..89ce87bd 100644
--- a/core/src/main/scala/org/scalatra/PathPatternParsers.scala
+++ b/core/src/main/scala/org/scalatra/PathPatternParsers.scala
@@ -44,7 +44,7 @@ trait PathPatternParser {
 
 object PathPatternParser {
 
-  val PathReservedCharacters = "/?#"
+  val PathReservedCharacters = "/?#%"
 
 }
 
diff --git a/core/src/main/scala/org/scalatra/UriDecoder.scala b/core/src/main/scala/org/scalatra/UriDecoder.scala
index 5955cea5..9e6c84ee 100644
--- a/core/src/main/scala/org/scalatra/UriDecoder.scala
+++ b/core/src/main/scala/org/scalatra/UriDecoder.scala
@@ -20,6 +20,7 @@ object UriDecoder {
     uri.replace("%23", "#")
       .replace("%2F", "/")
       .replace("%3F", "?")
+      .replace("%25", "%")
   }
 
 }
diff --git a/core/src/test/scala/org/scalatra/RouteTest.scala b/core/src/test/scala/org/scalatra/RouteTest.scala
index ee549270..a8a5dd2c 100644
--- a/core/src/test/scala/org/scalatra/RouteTest.scala
+++ b/core/src/test/scala/org/scalatra/RouteTest.scala
@@ -300,9 +300,9 @@ class RouteTest extends ScalatraFunSuite {
       body should equal("?query")
     }
 
-    get("/encoded-uri/Fu%C3%9Fg%C3%A4nger%C3%BCberg%C3%A4nge%2F%3F%23") {
+    get("/encoded-uri/Fu%C3%9Fg%C3%A4nger%C3%BCberg%C3%A4nge%2F%3F%23%25%253F") {
       status should equal(200)
-      body should equal("Fußgängerübergänge/?#")
+      body should equal("Fußgängerübergänge/?#%%3F")
     }
 
     get("/encoded-uri/ö%C3%B6%25C3%25B6") {

```
but it
- feels hackish
- breaks support for specifying routes which contains `%` signs, like the `encoded-uri-3` routes in `org.scalatra.RouteTestServlet`

#52 talks about something being discussed on IRC but I have no idea what was said and it was a long time ago.

I really don't want to reimplement named parameters in routes, and I'm suspecting that more applications out there could be susceptible for issues like ours.

**Comment by magnolia-k** [comment]
@ingemaradahl 

The results of investigating the behavior of Scalatra and other frameworks are summarized in the following links.

https://github.com/scalatra/scalatra/issues/969#issuecomment-533794181

In other framework examples, mixing a percentage-encoded URL in the path is often not handled properly, and is generally specified as a parameter (eg `http://path/to/site?url=https%3A%2F%2Fexample%2F%3Fid%3D%253F`).

In general, the contents of parameters are decoded on the application side.

Scalatra's path matching method is still a bit hacky at the moment, so I think it's better to adapt it to other frameworks.

Wouldn't it be more appropriate to stop inserting percent encoded URLs in the URL path?

**Comment by magnolia-k** [comment]
https://github.com/scalatra/scalatra/pull/985
