### ISSUE TITLE
Swagger doesn't support BasicAuth authorization (match error)

### ISSUE THREAD

**Issue by popojargo** [scalatra/scalatra#973]
Seems rather easy so implement. Would need to add the BasicAuth trait  and support it in the serializer here: https://github.com/scalatra/scalatra/blob/2.7.x/swagger/src/main/scala/org/scalatra/swagger/SwaggerBase.scala#L194

I'll try to do a pull request next week

**Comment by magnolia-k** [comment]
merged!
https://github.com/scalatra/scalatra/pull/974
