### ISSUE TITLE
Metrics feature not working

### ISSUE THREAD

**Issue by treaz** [scalatra/scalatra#991]
I've initialized a new project using sbt new scalatra/scalatra.g8 and I'm following the metrics docs from [here](http://scalatra.org//guides/2.6/monitoring/metrics.html).

**The issue** is that `context.mountMetricsAdminServlet("/metrics-admin")` or any other function from MetricsSupportExtensions are not avialable.

I've created a repo that showcases the issue: https://github.com/treaz/scalatra-metrics-issue

**Comment by treaz** [comment]
I've just found this unmerged issue in the docs page: https://github.com/scalatra/scalatra-website/pull/123. Turns out it's just a documentation issue

**Comment by takezoe** [comment]
Oh, that pull request was made in the era of Scalatra 2.4. We need to update docs for the latest version. Thanks for finding!

**Comment by treaz** [comment]
@takezoe I’d like to help with the docs. How can I help?

**Comment by takezoe** [comment]
Great thanks! Actually, I realized your message on https://github.com/scalatra/scalatra-website/issues/194 just now and replied immediately. Is my comment enough to get you started working? If there is something missing, feel free to contact me. I think Gitter might be a good place for this kind of communication: https://gitter.im/scalatra/scalatra
